-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 09/10/2024 às 03:41
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `pqp`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `produtos`
--

CREATE TABLE `produtos` (
  `CODIGO` int(11) NOT NULL,
  `NOME` varchar(50) DEFAULT NULL,
  `DESCRICAO` varchar(1000) DEFAULT NULL,
  `PRECO` decimal(7,2) DEFAULT NULL,
  `FOTO` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `produtos`
--

INSERT INTO `produtos` (`CODIGO`, `NOME`, `DESCRICAO`, `PRECO`, `FOTO`) VALUES
(1, 'Pimenta em pó picante', 'Ajuda na digestão, melhora a absorção de nutrientes, tem propriedades anti-inflamatórias e antioxidantes.', NULL, 'PIMENTAPO.JPEG'),
(2, 'Pimenta Jamaica', 'Rica em antioxidantes, auxilia na digestão, pode aliviar dores e possui propriedades anti-inflamatórias.', NULL, 'PIMENTAPOJAMAICA.JPEG'),
(3, 'Salsa Desidratada', 'Fonte de vitaminas A, C e K, fortalece o sistema imunológico, tem propriedades anti-inflamatórias e antioxidantes.', NULL, 'SALSADESIDRATADA.JPEG'),
(4, 'Chimichurri Defumado', 'Oferece antioxidantes, ajuda na digestão e adiciona um sabor defumado a pratos, melhorando sua complexidade.\r\n', NULL, 'CHIMICHURRI.JPEG'),
(5, 'Páprica defumada picante ', 'Rica em antioxidantes, melhora a circulação, tem propriedades anti-inflamatórias e ajuda a acelerar o metabolismo.', NULL, 'PAPRICADEFUPICANTE.JPEG'),
(6, 'Sálvia', 'Tem propriedades antioxidantes, melhora a memória, alivia inflamações e tem efeitos calmantes.', NULL, 'SALVIA.JPEG'),
(7, 'Sal do Himalaia ', 'Contém minerais essenciais, ajuda no equilíbrio eletrolítico do corpo, melhora a digestão e promove uma melhor hidratação.', NULL, 'SALIMALAIA.JPEG'),
(8, 'Orégano ', 'Rico em antioxidantes e vitaminas, melhora a digestão, tem propriedades antibacterianas e antifúngicas.', NULL, 'OREGANO.JPEG'),
(9, 'Cebolinha', 'Fonte de vitaminas A, C e K, melhora a digestão e tem propriedades antioxidantes e anti-inflamatórias.', NULL, 'CEBOLINHA.JPEG'),
(10, 'Manjericão', 'Rico em antioxidantes, melhora a digestão, tem propriedades anti-inflamatórias e pode ajudar a aliviar o estresse.', NULL, 'MANJERICAO.JPEG'),
(11, 'Chimichurri picante ', 'Contém antioxidantes, melhora a digestão, tem propriedades anti-inflamatórias e oferece um sabor picante.\r\n', NULL, 'CHIMICHURRIPIMENTA.JPEG'),
(12, 'Zattar', 'Mistura de especiarias rica em antioxidantes, ajuda na digestão e fortalece o sistema imunológico.\r\n', NULL, 'ZATTAR.JPEG'),
(13, 'Coentro em pó', 'Ajuda na digestão, tem propriedades desintoxicantes e anti-inflamatórias, além de melhorar a saúde da pele.', NULL, 'COENTROPO.JPEG'),
(14, 'Cominho em pó', 'Melhora a digestão, tem propriedades antioxidantes e anti-inflamatórias, além de ajudar a regular o açúcar no sangue.\r\n', NULL, 'COMINHOPO.JPEG'),
(15, 'Pimenta rosa em grão', 'Tem propriedades anti-inflamatórias e antioxidantes, melhora a circulação sanguínea e ajuda na digestão.\r\n', NULL, 'PIMENTAROSA.JPEG'),
(16, 'Edu Guedes', 'Mistura de especiarias com propriedades antioxidantes e digestivas, que contribuem para a saúde geral.', NULL, 'EDUGUEDES.JPEG'),
(17, 'Alho triturado ', 'Ajuda a fortalecer o sistema imunológico, tem propriedades anti-inflamatórias, antibacterianas e antioxidantes.', NULL, 'ALHOTRITURADO.JPEG'),
(18, 'Tempero para feijão Light', 'Contém ervas e especiarias que melhoram a digestão, com baixo teor de sódio, ideal para dietas leves.', NULL, 'TEMPEIROFEIJAO.JPEG'),
(19, 'Lemon ervas', 'Rico em antioxidantes, ajuda a melhorar a digestão e a circulação, além de oferecer um sabor cítrico refrescante.', NULL, 'LEMONERVAS.JPEG'),
(20, ' Orange Pepper', 'Contém antioxidantes, melhora a digestão e tem um sabor cítrico que complementa diversos pratos.', NULL, 'ORANGEPEPPER.JPEG'),
(21, 'Pimenta do reino preta em grão', 'Aumenta a produção de ácido clorídrico no estômago. O ácido clorídrico é necessário para digerir alimentos e absorção de nutrientes. A Pimenta preta também é uma boa fonte de ferro.', NULL, 'PIMENTAGRAO.JPEG'),
(22, 'Páprica doce', 'Rica em antioxidantes, melhora a circulação e tem propriedades anti-inflamatórias suaves.', NULL, 'PAPRICADOCE.JPEG'),
(23, 'Tempero baiano ', 'Mistura de especiarias que melhora a digestão, tem propriedades anti-inflamatórias e antioxidantes.', NULL, 'TEMPEROBAIANO.JPEG'),
(24, 'Alho em pó', 'Ajuda a fortalecer o sistema imunológico, tem propriedades antibacterianas e anti-inflamatórias.', NULL, 'ALHOPO.JPEG'),
(25, 'Nós moscada em pó', 'Melhora a digestão, tem propriedades calmantes, antioxidantes e anti-inflamatórias.', NULL, 'NOSMOSCADAPO.JPEG'),
(26, 'Edu Guedes light ', 'Mistura leve com ervas e especiarias que melhoram a digestão, sem excessos de sódio, ideal para dietas saudáveis.\r\n', NULL, 'EDUGLIGHT.JPEG'),
(27, 'Pega marido', 'Mistura de especiarias que oferece benefícios digestivos e antioxidantes, além de melhorar o sabor dos pratos.', NULL, 'PEGAMARIDO.JPEG'),
(28, 'Páprica defumada doce ', 'Rica em antioxidantes, tem propriedades anti-inflamatórias e melhora a circulação.', NULL, 'PAPRICADEFUMADADOCE.JPEG'),
(29, 'Creme de cebola ', 'Fonte de sabor e textura, ajuda a melhorar a digestão e tem propriedades antioxidantes.', NULL, 'CREMECEBOLA.JPEG'),
(30, 'Caldo de legume ', 'Oferece nutrientes essenciais, ajuda a melhorar a digestão e pode fortalecer o sistema imunológico.', NULL, 'CALDOLEGUME.JPEG'),
(31, 'Caldo de galinha ', 'Rico em minerais, ajuda na digestão e pode fortalecer o sistema imunológico.\r\n', NULL, 'CALDOGALINHA'),
(32, 'Ana Maria light', 'Mistura leve de especiarias que melhora a digestão e oferece benefícios antioxidantes.', NULL, 'ANAMARIALI.JPEG'),
(33, 'Alho frito triturado', 'Ajuda a fortalecer o sistema imunológico, tem propriedades anti-inflamatórias e antioxidantes, além de adicionar crocância.', NULL, 'ALHOTRITFRITO.JPEG'),
(34, 'Açafrão da terra', 'Rico em antioxidantes, melhora a digestão e tem fortes propriedades anti-inflamatórias.', NULL, 'ACAFRAOTERRA.JPEG'),
(35, 'Alho,Cebola e Salsa', 'Combinação que fortalece o sistema imunológico, melhora a digestão e oferece antioxidantes.', NULL, 'ALHOCEBOLASALSA.JPEG'),
(36, 'Caldo de carne', 'Fonte de proteínas e minerais, ajuda a fortalecer o sistema imunológico e a melhorar a digestão.', NULL, 'CALDOCARNE.JPEG'),
(37, 'Aroma de fumaça', 'Adiciona sabor defumado sem adicionar calorias ou gorduras, melhora a complexidade dos pratos.', NULL, 'AROMAFUMACA.JPGE'),
(38, 'Pimenta calabresa', 'Tem propriedades anti-inflamatórias, melhora a circulação e acelera o metabolismo.\r\n', NULL, 'PIMENTACALABRESA.JPEG'),
(39, 'Cebola crispy', 'Oferece sabor e textura crocânte, além de propriedades antioxidantes.', NULL, 'CEBOLACRISPY.JPEG'),
(40, 'Cebola em pó', 'Ajuda a melhorar a digestão, tem propriedades antioxidantes e anti-inflamatórias.', NULL, 'CEBOLAPO'),
(41, 'Caldo de costela em pó', 'Rico em sabor e minerais, ajuda a fortalecer o sistema imunológico e a melhorar a digestão.', NULL, 'CALDOCOSTELA.JPEG'),
(42, 'Páprica picante ', 'Rica em antioxidantes, melhora a circulação, acelera o metabolismo e tem propriedades anti-inflamatórias.', NULL, 'PAPRICAPICANTE.JPEG'),
(43, 'Tempero do chef com páprica', 'Mistura que combina antioxidantes e propriedades digestivas, ideal para intensificar o sabor dos pratos.', NULL, 'TEMPEROCHEFEPAPRICA.JPEG'),
(44, 'Lemon pepper', 'Contém antioxidantes, melhora a digestão, oferece um sabor cítrico e é ideal para peixes e frango.', NULL, 'LEMOMPEPPER.JPEG'),
(45, 'Colorau', 'Tem propriedades antioxidantes, ajuda a melhorar a circulação e oferece um sabor suave e adocicado aos pratos.', NULL, 'COLORAU.JPEG'),
(50, 'Bio2 Banana', 'Previne doenças cardiovasculares, ajuda no controle do estresse e no sono, fornece saciedade, é benéfica para o sistema digestivo e para a saúde ocular.', NULL, 'BIO2BANANA.JPEG'),
(51, 'Bio2 Cacau', 'É fonte de magnésio, mineral importante para a saúde cardiovascular e metabolismo energético. ', NULL, 'BIO2CACAU.JPEG'),
(52, 'Bio2 Coco', 'Contém potássio, sódio, fósforo e cloro e fibras que estimulam da atividade intestinal. O coco ainda contém gorduras essenciais que participam de diversas reações no corpo.', NULL, 'BIO2COCO.JPEG'),
(53, 'Bio2 Crunchydark', 'Rico em proteínas e fonte de fibras: 12g de proteínas e 9g de fibras por barra. Com muita crocância. Opção de lanche prático e nutritivo. Pode ser consumido entre as principais refeições.', NULL, 'BIO2CRUNCHYDARK.JPEG'),
(54, 'Bio2 Damasco', 'É uma excelente fonte de fibras, é rico em minerais como o potássio e o ferro e possui alta concentração de carotenóides, especialmente o betacaroteno, um importante antioxidante, além de fornecer altos níveis de vitamina A e C.', NULL, 'BIO2DAMASCO.JPEG'),
(55, 'Amendoim apimentado', 'Tem efeito antioxidante nas membranas celulares. Contribui melhorando a síntese de proteínas.\r\nAjuda a reforçar os valores de ácido fólico e é ideal para mulheres grávidas, desde que seja consumido moderadamente.', NULL, 'AMENDOIMPIMENTA.JPEG'),
(56, 'Amendoim com pele e sal', 'O amendoim é uma oleaginosa que pode trazer vários benefícios para a saúde, como ajudar a diminuir a inflamação no corpo, prevenir doenças cardiovasculares, combater a anemia, prevenir o envelhecimento prematuro e melhorar o humor, já que é rico em compostos antioxidantes, além de ter boas quantidades de nutrientes, como as vitaminas do complexo B, vitamina E, aminoácidos e gorduras saudáveis.', NULL, 'AMENDOIMCOMPELECOMSAL.JPEG'),
(57, 'Amendoim cebola e salsa', 'É rico em ômega-3 e outras gorduras boas, o que ajuda a reduzir a inflamação do corpo e protege o coração', NULL, 'AMENDOIMVERDE.JPEG'),
(58, 'Amendoim sem pele', 'É rico em vitaminas B e E, e é um antioxidante natural, por exemplo, que ajuda a combater os radicais livres e prevenir o envelhecimento precoce. É benéfico também no combate da anemia, já que possui ácido fólico, uma vitamina que estimula a formação de glóbulos vermelhos no sangue.', NULL, 'AMENDOIMSEMPELESEMSAL.JPEG'),
(59, 'Amendoim doce', ' O amendoim é rico em proteínas e gorduras, tem um alto potencial energético, oferece aminoácidos essenciais, além de ser um dos alimentos vegetais mais ricos em cálcio e fósforo.', NULL, 'AMENDOIMDOCE.JPEG'),
(60, 'Amendoim crocante ', 'Rico em nutrientes como proteínas e gorduras, capaz de suprir as necessidades diárias de vitamina E, vitamina B1, vitamina B3, enxofre, sódio, magnésio, cobre, ferro e fósforo..', NULL, 'AMENDOIMCROCANTE.JPEG'),
(61, 'Amendoim sem pele com sal e alho', 'Fonte de proteínas, magnésio e potássio, portanto o Amendoim com alho é muito recomendado para quem pratica exercícios físicos, pois ajuda a manter a saúde dos músculos, no aumento de massa muscular e também melhora o rendimento durante o treino.', NULL, 'AMENDOIMSEMPELESALALHO.JPEG'),
(62, 'Amendoim japonês ', 'Fornece ao corpo grande quantidade de nutrientes; Ajuda a desinfetar as vias respiratórias; Tem efeito antioxidante nas membranas celulares; Contribui melhorando a síntese de proteínas.', NULL, 'AMENDOIMJAPONES.JPEG'),
(63, 'Amendoim drageado', ' Equilibra crocância com o sabor amargo do chocolate.', NULL, 'AMENDOIMDRAGEADO.JPEG'),
(64, 'Alfajor Avelã ', 'É um doce indulgente, com camadas ricas e texturas diferentes.', NULL, 'ALFAJORAVELA.JPEG'),
(65, 'Avelã craqueado capuchino ', 'Avelãs são uma boa fonte de fibra alimentar. Comer muitas fibras estimula os movimentos intestinais regulares e ajuda a prevenir a constipação.', NULL, 'AVELACRAQUEADOCAPUCHINO.JPEG'),
(66, 'Bala de goma', 'Balas de goma são doces coloridos e divertidos, perfeitos para qualquer momento.', NULL, 'BALAGOMA.JPEG'),
(67, 'Banana cristalizada', 'Fonte rápida de energia e rica em potássio, ideal para atividades físicas ou como lanche rápido.', NULL, 'BANANACRISTALIZADA.JPEG'),
(68, 'Banana drageado zero açúcar', 'É uma opção saudável, sem açúcar, mas cheia de sabor.', NULL, 'BANANADRAGEADOLEITEZERO.JPEG'),
(69, 'Barra de chocolate Only 70% ', 'Oferece o contraste entre o doce do chocolate e o azedinho da cranberry.', NULL, 'BARRACHOCOLATEONLY.JPEG'),
(70, 'Barra de chocolate Only coco 70%', 'traz uma opção com pedacinhos crocantes de coco, realçando o sabor do chocolate.', NULL, 'BARRACHOCOLATEONLYCOCO.JPEG'),
(71, 'Barra Laciella 70%', 'uma opção sem lactose e com alto teor de cacau, ideal para quem tem restrições alimentares.\r\n', NULL, 'BARRALACIELLA.JPEG'),
(72, 'Barra Laciella cacau 70% ', 'É uma alternativa saudável, rica em cacau.', NULL, 'BARRALACIELLACACAU.JPEG'),
(73, 'Biscoito de amendoim creme e avelã ', 'Promove a recuperação e desenvolvimento muscular, protege o sistema nervoso, tem ação antioxidante, previne anemia, entre muitos outros benefícios.', NULL, 'BISCOITOAMENDOIMCREMEAVELA.JPEG'),
(74, 'Café drageado', 'Combina o aroma marcante do café com o chocolate, agradando aos amantes de café.', NULL, 'CAFEDRAGEADO.JPEG'),
(75, 'Castanha de caju Blend 70%', 'Combina a intensidade do chocolate amargo com o sabor suave das castanhas de caju.', NULL, 'CASTANHACAJUBLEND.JPEG'),
(76, 'Castanha de caju caramelizada', 'Oferece uma mistura de crocância com um toque doce do caramelo.\r\n', NULL, 'CASTANHACAJUCARAMELIZADA.JPEG'),
(77, 'Castanha de caju drageado zero açúcar ', 'É uma combinação cremosa e crocante, com o equilíbrio perfeito entre o doce e o salgado.', NULL, 'CASTANHACAJUDRAGEADOZERO.JPEG'),
(78, 'Chocoball ao leite ', 'É um doce com uma crocância agradável e sabor de chocolate ao leite.', NULL, 'CHOCOBALLAOLEITE.JPEG'),
(79, 'Barra de chocolate branco', 'Oferece uma opção deliciosa sem açúcar, mantendo o sabor suave e doce do chocolate branco.', NULL, 'CHOCOLATEBARRABRANCO.JPEG'),
(80, 'Damasco com café e laranja zero açúcar ', 'A combinação do damasco doce e suculento com a intensidade do café e o frescor da laranja cria um contraste perfeito, realçado pelo chocolate de alta qualidade. Com zero açúcar, esta drágea proporciona o prazer de um doce sofisticado sem comprometer sua saúde. A cada mordida, você sentirá a harmonia entre o amargor suave do café, a acidez refrescante da laranja e a doçura natural do damasco, envoltos pela cremosidade do chocolate.', NULL, 'DAMASCOCAFELARANJAZERO.JPEG'),
(81, 'Damasco com chocolate zero açúcar', ' Mistura doce e ácido, criando um contraste saboroso.\r\n', NULL, 'DAMASCOCHOCOLATEZERO.JPEG'),
(82, 'Florzinha amantegada', 'São crocantes e delicadas, ideais para um lanche leve e saboroso.', NULL, 'FLORZINHAMANTEGADA.JPEG'),
(83, 'Goma acida ', 'Goma ácida oferece um toque refrescante e azedo para quem gosta de sabores mais intensos.', NULL, 'GOMAACIDA.JPEG'),
(84, 'Gotas de chocolate Belga ', 'Oferecem um sabor intenso e refinado, perfeito para quem aprecia um bom chocolate.', NULL, 'GOTASCHOCOLATEBELGA.JPEG'),
(85, 'Gotas de chocolate zero açúcar ', 'Proporcionam o sabor clássico do chocolate ao leite, sem adição de açúcar.', NULL, 'GOTASCHOCOLATEZERO.JPEG'),
(86, 'Licor de cereja ', 'Proporciona uma explosão de sabores com o licor de cereja envolvido em chocolate.', NULL, 'LICORCEREJA.JPEG'),
(87, 'Morango drageado com licor ', 'Delicie-se com a combinação perfeita de chocolate e licor de morango, oferecendo um sabor sofisticado e inesquecível.', NULL, 'MORANGODRAGEADOLICOR.JPEG'),
(88, 'Morango gourmet drageado ', 'Delicioso e super macio.', NULL, 'MORANGOGOURMETDRAGEADO.JPEG'),
(89, 'Mousse de maracujá drageado ', 'Além de ser delicioso, o mousse de maracujá pode ajudar a reduzir o estresse. A fruta contém alcaloides e flavonoides, que possuem efeitos relaxantes, ajudando a acalmar a mente e o corpo. Auxilia na Digestão: O maracujá é rico em fibras, que ajudam a regular o sistema digestivo', NULL, 'MOUSSEDEMARACUJADRAGEADO.JPEG'),
(90, 'Pistache com chocolate ', 'Pistache com chocolate zero açúcar é uma opção deliciosa sem adição de açúcar, ideal para quem busca alternativas mais saudáveis.', NULL, 'PISTACHECHOCOLATE.JPEG'),
(91, 'Rock cracker com pasta de amendoim ', 'Mistura a crocância dos biscoitos com a cremosidade do amendoim.', NULL, 'ROCKCRACKERPASTAAMENDOIM.JPEG'),
(92, 'Tâmara com castanha do Pará ', 'Com castanha oferece um toque doce natural da tâmara, complementado pelo chocolate amargo e crocância das castanhas.', NULL, 'TAMARACASTANHAPARA.JPEG'),
(93, 'Tiramissu drageado', 'Oferece um sabor intenso e sofisticado, com alto teor de cacau.\r\n', NULL, 'TIRAMISSUDRAGEADO.JPEG'),
(94, 'Bold avelã branco ', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDAVELABRANCO.JPEG'),
(95, 'Bold berries crispie', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDBERRIESCRISPIES.JPEG'),
(96, 'Bold café com doce de leite ', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDCAFEDOCELEITE.JPEG'),
(97, 'Bold caramelo', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDCARAMELO.JPEG'),
(98, 'Bold cookies black ', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDCOOKIESBLACK.JPEG'),
(99, 'Bold cookies cream', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDCOOKIESCREAM.JPEG'),
(100, 'Bold crunch caramelo e chocolate ', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDCRUNCH.JPEG'),
(101, 'Bold leite e avelã', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDLEITEAVELA.JPEG'),
(102, 'Bold thin ', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDTHIN.JPEG'),
(103, 'Bold torta de limão ', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDTORTALIMAO.JPEG'),
(104, 'Bold trufa de chocolate ', 'É rica em fibras, favorecendo a saciedade e a saúde digestiva. Perfeita para o pré-treino ou como um snack pós-treino, ajuda a manter sua energia e recuperação muscular, sem comprometer o paladar.', NULL, 'BOLDTRUFACHOCOLATE.JPEG'),
(105, 'Mulkebar cookies e crean', 'Está pronta para auxiliar na sua recuperação muscular da forma mais saborosa possível', NULL, 'MULKEBARCOOKIESCREAN.JPEG'),
(106, 'Nutrata whey de morango', 'Maior recuperação muscular, diminuição do dano muscular durante o exercício. Aumento da síntese de proteína após o treino.', NULL, 'NUTRATAHEYMORANGO.JPEG'),
(107, 'Nutrata whey de doce de leite', 'Maior recuperação muscular, diminuição do dano muscular durante o exercício. Aumento da síntese de proteína após o treino.', NULL, 'NUTRATAWHEYDOCELEITE.JPEG'),
(108, 'Protein crisp cookies e cream', 'Ótima fonte de vitaminas, minerais e fibras, ajuda a saciar a fome e evitar o catabolismo. Pode ser facilmente encaixada em dietas para emagrecimento.', NULL, 'PROTEINCRISPCOOKIESCREAM.JPEG'),
(109, 'Protein crisp trufa de avelã ', 'Ótima fonte de vitaminas, minerais e fibras, ajuda a saciar a fome e evitar o catabolismo. Pode ser facilmente encaixada em dietas para emagrecimento.', NULL, 'PROTEINCRISPTRUFAAVELA.JPEG'),
(110, 'All bran ', 'Ajuda a reduzir o colesterol, manter um peso corporal saudável e promover a regularidade.', NULL, 'ALLBRAN.JPEG'),
(111, 'Amaranto em flocos ', 'Inibe o funcionamento de enzimas que elevam a pressão arterial, controlando os níveis em números saudáveis. ', NULL, 'AMARANTOFLOCOS.JPEG'),
(112, 'Aveia em flocos', ' contém antioxidantes que ajudam a diminuir a pressão arterial, por isso, contribui na prevenção de casos de infarto e outros problemas cardíacos. O cereal também auxilia na saúde digestiva e atua na redução dos índices de colesterol ruim, graças à presença de uma fibra chamada beta-glucana.', NULL, 'AVEIAFLOCOS.JPEG'),
(113, 'Aveia laminada ', ' contém antioxidantes que ajudam a diminuir a pressão arterial, por isso, contribui na prevenção de casos de infarto e outros problemas cardíacos. O cereal também auxilia na saúde digestiva e atua na redução dos índices de colesterol ruim, graças à presença de uma fibra chamada beta-glucana.', NULL, 'AVEIALAMINADA.JPEG'),
(114, 'Aveia em farelo ', ' contém antioxidantes que ajudam a diminuir a pressão arterial, por isso, contribui na prevenção de casos de infarto e outros problemas cardíacos. O cereal também auxilia na saúde digestiva e atua na redução dos índices de colesterol ruim, graças à presença de uma fibra chamada beta-glucana.', NULL, 'FARELOAVEIA.JPEG'),
(115, 'Arroz em flocos ', ' Possui carboidratos complexos, fibras, vitaminas do complexo B e minerais. Comprar flocos de arroz e contar com este alimento rico em sua alimentação fará bem para o coração, circulação, músculos e sistema digestivo.', NULL, 'FLOCOSARROZ.JPEG'),
(116, 'Granola de cacau ', ' Rica em proteínas, fibras, vitaminas e minerais como ferro, cálcio, potássio, zinco e magnésio, além de fornecer calorias que ajudam no aumento de energia e disposição para as atividades do dia-a-dia.', NULL, 'GRANOLACACAU.JPEG'),
(117, 'Granola tradicional ', ' Rica em proteínas, fibras, vitaminas e minerais como ferro, cálcio, potássio, zinco e magnésio, além de fornecer calorias que ajudam no aumento de energia e disposição para as atividades do dia-a-dia.', NULL, 'GRANOLATRADICIONAL.JPEG'),
(118, 'Sucrilhos diet', 'Fonte rápida de carboidratos para energia, ideal para começar o dia com um café da manhã simples.', NULL, 'SUCRILHOSDIET.JPEG'),
(119, 'Batata mexicana de cebola ', ' Possui impressionantes propriedades antidepressivas e anabolizantes, sendo usada também para combater o envelhecimento precoce. Ela é perfeita para um lanche e uma refeição rápida.', NULL, 'BATATAMEXICANACEBOLA.JPEG'),
(120, 'Batata mexicana de churrasco ', 'É uma excelente fonte de vitaminas (especialmente vitamina A, na forma de beta-caroteno), minerais (como potássio e manganês), e fibras. Antioxidantes: Contém antioxidantes que ajudam a proteger o corpo contra danos dos radicais livres e reduzir o risco de doenças crônicas.', NULL, 'BATATAMEXICANACHURASCO.JPEG'),
(121, 'Biscoito de arroz barbecue picante ', 'É uma ótima opção para quem quer emagrecer ou está passando por uma reeducação alimentar, já que afasta a fome e ainda possui baixas calorias. O alimento pode ser consumido no café da manhã ou como lanche intermediário, além de poder ser combinado com outros ingredientes.', NULL, 'BISCOITOARROZBARBPICANTE.JPEG'),
(122, 'Chips de banana', 'Fornece energia de fácil assimilação, Fonte de minerais como o potássio, fósforo, magnésio, rico em triptofano, fonte de Vitaminas A e do complexo B e ajuda na saciedade.', NULL, 'CHIPSBANANA.JPEG'),
(123, 'Chips de batata doce ', 'Aumenta a saciedade, colaborando no processo de emagrecimento; ajuda no controle do colesterol, prevenindo futuras doenças cardiovasculares.', NULL, 'CHIPSBATATADOCE.JPEG'),
(124, 'Chips de maçã', 'Possui vitaminas A e C, que atuam no bem estar da pele e dos ossos, além de diversos tipos de vitamina B, que ajudam na manutenção do metabolismo.', NULL, 'CHIPSMACA.JPEG'),
(125, 'Chips de madioquinha ', 'Fornece energia para o corpo, é de fácil digestão, possui vitaminas do complexo B, C, E, além de ter fósforo que é muito importante para o metabolismo ósseo.', NULL, 'CHIPSMANDIOQUINHA.JPEG'),
(126, 'Chips de vegetais desidratado ', 'São ótimos aliados na nutrição do dia a dia por apresentarem uma grande quantidade de nutrientes.', NULL, 'CHIPSVEGETAISDESIDRATADO.JPEG'),
(127, 'Milho torrado com mel e mostarda ', 'É um alimento rico em nutrientes por conta das propriedades do milho, sendo boa fonte de energia, além de contar com quantidades consideráveis de vitaminas B1, E e sais minerais.', NULL, 'MILHOTORRADOMOSTARDA.JPEG'),
(128, 'Provolone crocante romeu e julieta ', 'Eles são ótimas fontes e cálcio, importante para a manutenção de ossos e dentes, proteínas, necessárias para o desenvolvimento do organismo, e em vitaminas A, importante para a visão, e B12, imprescindível para a função neurológica normal.', NULL, 'PROVOLONECROCANTEROMEUJULIETA.JPEG'),
(129, 'Artri flex', 'Suplemento para a saúde das articulações, contendo ingredientes que ajudam a reduzir inflamações e melhorar a flexibilidade.', NULL, 'ARTRIFLEX.JPEG'),
(130, 'Bio ferro ', 'Suplemento de ferro que ajuda na prevenção e tratamento da anemia. A vitamina C melhora a absorção do ferro', NULL, 'BIOFERRO.JPEG'),
(131, 'Bio vitamina B+', 'Auxiliam no funcionamento do sistema imune, no metabolismo do ferro e na visão.', NULL, 'BIOVITAMINAB+.JPEG'),
(132, 'Bio zinco aminoácido ', 'O zinco é essencial para o sistema imunológico, cicatrização e síntese de proteínas. Os aminoácidos são os blocos de construção das proteínas.', NULL, 'BIOZINCOAMINOACIDO.JPEG'),
(133, 'Coenzima 10 antioxidante', 'É melhorar as funções operacionais e prevenir doenças associadas à oxidação das células. Isso inclui o Alzheimer e o Parkinson.', NULL, 'COENZIMA10ANTIOXIDANTE.JPEG'),
(134, 'Colagen verisol', 'Estimula a produção de colágeno na pele, ajudando a melhorar a elasticidade, hidratação e firmeza da pele.', NULL, 'COLAGENVERISOL.JPEG'),
(135, 'COQ 10', 'Poderoso antioxidante que auxilia na produção de energia celular e na proteção das células contra o estresse oxidativo.', NULL, 'COQ10.JPEG'),
(136, 'Curcuma plus ', 'A cúrcuma tem propriedades anti-inflamatórias e antioxidantes, auxiliando na saúde das articulações e no sistema digestivo.', NULL, 'CURCUMAPLUS.JPEG'),
(137, 'Flex sensor ', 'Promove a saúde das articulações, ajudando na mobilidade e no alívio de dores articulares.', NULL, 'FLEXSENSOR.JPEG'),
(138, 'Magnésio dimalato  ', 'Ajuda no alívio da fadiga muscular, melhorando a produção de energia e a saúde do sistema nervoso.', NULL, 'MAGNESIODIMALATO.JPEG'),
(139, 'Magnésio treonato ', 'Contribui para a saúde cerebral e melhora da função cognitiva, sendo uma forma de magnésio facilmente absorvida.', NULL, 'MAGNESIOTREONATO.JPEG'),
(140, 'Mega Dha suplemento alimentar ', ' O DHA é um tipo de ômega 3 essencial para a saúde cerebral, ocular e função cognitiva.', NULL, 'MEGADHASUPLEMENTOALIMENTAR.JPEG'),
(141, 'Melatonina ', 'A melatonina é um hormônio que regula o sono, enquanto o triptofano é um precursor da serotonina, ajudando na melhora da qualidade do sono e no humor.', NULL, 'MELATONINA.JPEG'),
(142, 'Moro redux ', ' Auxilia no controle de peso, promovendo a queima de gordura abdominal e ajudando no metabolismo lipídico.', NULL, 'MOROREDUX.JPEG'),
(143, 'Ômega 3 Epa Deha', 'Proporciona benefícios para a saúde do coração, cérebro e articulações, ajudando a reduzir inflamações e melhorar as funções cognitivas.', NULL, 'OMEGA3EPADHA.JPEG'),
(144, 'Ômega 3-6-9', 'Contribui para a saúde cardiovascular, função cerebral e redução de inflamações. Ajuda a manter o equilíbrio entre os ácidos graxos essenciais para o corpo.', NULL, 'OMEGA369.JPEG'),
(146, 'Spirulina orgânica ', ' Rica em proteínas, vitaminas, minerais e antioxidantes. Ajuda na desintoxicação do corpo, na saúde cardiovascular e no fortalecimento do sistema imunológico.', NULL, 'SPIRULINAORGANICA'),
(147, 'Vitamina C lipossomal ', 'Natural, antioxidante e com absorção otimizada da vitamina C. Auxilia no funcionamento do sistema imunológico.', NULL, 'VITAMINACLIPOSSOMAL.JPEG'),
(148, 'Vitamina bio2 Metilcobalamina ', 'Ajuda a promover o funcionamento adequado dos neurônios.', NULL, 'VITBIO2METILCOBALAMINA.JPEG'),
(149, 'Energético de catuaba ', 'Aumenta a energia física e mental,reduz o cansaço e a fadiga, aumenta a vitalidade e a libido, melhora a memória e a disposição', NULL, 'CATUABA.JPEG'),
(150, 'Energético guaraná em pó', 'Aumenta a disposição e o estado de alerta por conter alto teor de cafeína, teobromina e teofilina, compostos bioativos que são estimulantes e que retardam a sensação de cansaço físico, melhorando o rendimento durante o trabalho ou os treinos.', NULL, 'GUARANAPO.JPEG'),
(151, 'Energético maçã peruana negra ', 'É um poderoso estimulante natural, ideal para aumentar a vitalidade e combater o cansaço do dia a dia.', NULL, 'MACAPERUANANEGRA.JPEG'),
(152, 'Energético moring shot ', 'O seu consumo diário fortalece o sistema imunológico, dificultando a entrada de organismos nocivos causadores de doenças, como a gripes e os resfriados.', NULL, 'MORNINGSHOT.JPEG'),
(154, 'Energético sleepkoala de chocolate ', 'Uma bebida deliciosa para quem deseja suplementar a alimentação antes de dormir e que traz conforto para os seus rituais noturnos.', NULL, 'SLEEPKOALACHOCOLATE.JPEG'),
(155, 'Energético supercoffee de chocolate', 'Mais do que um simples café, pré-treino ou energético comum, o SuperCoffee é uma bebida energética natural ótima para o corpo, mente, saúde, e bem-estar diário.', NULL, 'SUPERCOFFEECHOCOLATE.JPEG'),
(156, 'Energético supercoffee original ', 'Promove clareza mental, hiperfoco e concentração.', NULL, 'SUPERCOFFEEORIGINAL.JPEG'),
(157, 'Ameixa sem caroço ', 'Rica em fibras, especialmente pectina, ajuda na regulação intestinal e no controle do colesterol.', NULL, 'AMEIXASEMCAROCO.JPEG'),
(158, 'Casca de limão cristalizada ', 'Ricas em vitamina C e compostos antioxidantes, oferecem um toque refrescante e ajudam na imunidade.', NULL, 'CASCALIMAOCRISTALIZADA.JPEG'),
(159, 'Damasco ', 'Rico em fibras e vitamina A, ajuda na saúde da pele, visão e sistema digestivo.', NULL, 'DAMASCO.JPEG'),
(160, 'Gengibre glaceado ', 'Ajuda na digestão, combate náuseas e tem propriedades anti-inflamatórias.', NULL, 'GENGIBREGLACEADO.JPEG'),
(161, 'Laranja desidratada ', 'Rica em vitamina C, ajuda a fortalecer o sistema imunológico e tem um sabor refrescante e cítrico. Pode ser adicionada a chás para dar um toque aromático e melhorar o sabor.', NULL, 'LARANJADESIDRATADA.JPEG'),
(162, 'Uva passa clara ', 'Fonte de energia rápida e rica em antioxidantes, contribui para a saúde do coração e do sistema digestivo.', NULL, 'UVAPASSACLARA.JPEG'),
(163, 'Uva passa escura ', 'Fonte de antioxidantes e ferro, auxilia na circulação sanguínea e combate a fadiga.', NULL, 'UVAPASSAESCURA.JPEG'),
(164, 'Granola cranberry ', ' O cranberry é conhecido por seus benefícios antioxidantes, ajudando a fortalecer o sistema imunológico.', NULL, 'GRANOLACRANBERRY.JPEG'),
(175, 'Batata mexicana tradicional  ', ' Possui impressionantes propriedades antidepressivas e anabolizantes, sendo usada também para combater o envelhecimento precoce. ', NULL, 'BATATAMEXICANATRADICIONAL.JPEG'),
(176, 'Biscoito de linhaça com queijo ', ' Rico em Fibras, promove uma digestão saudável e sensação de saciedade. Sabor Delicioso! O aroma do queijo complementa a crocância da linhaça, tornando cada mordida saborosa. Praticidade: Ideal para lanches rápidos em casa, no trabalho ou na escola.', NULL, 'BISCOITOLINHACAQUEIJO.JPEG'),
(177, 'Casca de laranja cristalizada ', 'Fonte de vitamina C e fibras, contribuem para a saúde imunológica e digestiva.\r\n', NULL, 'CASCALARANJACRISTALIZADA.JPEG'),
(178, 'Chá de alecrim ', 'Possui propriedades estimulantes, ajudando a melhorar a circulação e aliviar dores musculares. Também pode melhorar a memória e a concentração.', NULL, 'ALECRIM.JPEG'),
(179, 'Chá de alfazema ', 'É conhecida por suas propriedades relaxantes e calmantes, sendo eficaz no alívio de insônia, estresse e ansiedade. Também pode ser usada para aliviar dores de cabeça e tensão muscular.', NULL, 'ALFAZEMA.JPEG'),
(180, 'Chá de amora ', 'serve para aliviar os sintomas da menopausa, controlar a pressão alta, prevenir a diabetes, fortalecer o sistema imunológico.', NULL, 'AMORA.JPEG'),
(181, 'Chá de anis-estrelado ', 'Possui ação digestiva, ajudando a aliviar problemas como gases e má digestão. Também tem propriedades antimicrobianas e pode fortalecer o sistema imunológico.', NULL, 'ANIESTRELADO.JPEG'),
(182, 'Chá de aroeira ', 'Conhecido por suas propriedades anti-inflamatórias, é utilizado no tratamento de problemas digestivos e infecções. Também pode ajudar a melhorar a saúde da pele.\r\n', NULL, 'AROEIRA.JPEG'),
(183, 'Chá de barbatimão ', 'Tem ação adstringente e anti-inflamatória, sendo eficaz no tratamento de feridas, inflamações e problemas de pele. Também pode ser útil no combate a infecções.', NULL, 'BARBATIMAO.JPEG'),
(184, 'Chá de boldo ', 'É excelente para a digestão, ajudando no funcionamento do fígado e aliviando sintomas de indigestão. Também tem propriedades detoxificantes, contribuindo para a eliminação de toxinas.', NULL, 'BOLDO.JPEG'),
(185, 'Chá buchinha-do-norte ', 'Utilizada tradicionalmente como descongestionante nasal, ajudando a aliviar sintomas de sinusite. Também pode ter propriedades antimicrobianas.\r\n', NULL, 'BUCHINHANORTE.JPEG'),
(186, 'Chá de camomila ', 'Tem efeito calmante, sendo ideal para aliviar o estresse, a ansiedade e melhorar a qualidade do sono. Também é benéfica para a digestão.', NULL, 'CAMOMILA.JPEG'),
(187, 'Chá canela de pau ', 'Contribui para a diminuição da resistência insulínica, hormônio relacionado ao metabolismo do açúcar. Além disso, a canela tem uma excelente atividade anti-inflamatória, por isso pode ajudar a diminuir o acúmulo de gordura e auxiliar no processo de emagrecimento.', NULL, 'CANELAPAU.JPEG'),
(188, 'Chá de canela em pó', 'Ajuda a melhorar a circulação sanguínea, além de ter propriedades antioxidantes e anti-inflamatórias. Também pode contribuir para o controle dos níveis de açúcar no sangue.', NULL, 'CANELAPO.JPEG'),
(189, 'Chá canela de velho ', ' É indicada para tratar doenças dolorosas como artrites, artroses e reumatismo. Mas também ajuda a aliviar dores de tendinites, torcicolos.', NULL, 'CANELAVELHO.JPEG'),
(190, 'Chá de capim cidrão ', 'Propriedades calmantes e sedativas, que ajudam o organismo a acalmar e relaxar; Além disso, o chá possui ação antioxidante, anti-inflamatória, analgésica e pode ajudar na produção do leite materno.', NULL, 'CAPIMCIDRAO.JPEG'),
(191, 'Chá de carqueja amarga ', 'Tem efeitos hepatoprotetores e antioxidantes. Além disso, a carqueja é indicada como tônico estomáquico, antidiarreico, antirreumático, entre outras possibilidades.', NULL, 'CARQUEJAAMARGA.JPEG'),
(192, 'Chá de cavalinha', 'Possui propriedades diuréticas, auxiliando na eliminação de líquidos e toxinas. Também é benéfica para a saúde da pele e dos cabelos, e contribui para a saúde óssea.', NULL, 'CAVALINHA.JPEG'),
(193, 'Chá cravo-da-índia ', 'Tem ação antioxidante e anti-inflamatória, sendo ótimo para o sistema digestivo e para fortalecer o sistema imunológico. Também tem propriedades analgésicas e antissépticas.', NULL, 'CRAVODAINDIA.JPEG'),
(194, 'Chá de cravo em pó', 'Melhora a digestão, ajuda a controlar a diarreia e a diminuir a flatulência, ajuda na regulação de açúcar no sangue,fortalece o sistema imunológico.\r\n', NULL, 'CRAVOPO.JPEG'),
(195, 'Chá de dente de leão', 'Possui propriedades diuréticas e desintoxicantes, ajudando a eliminar toxinas do organismo. Também pode auxiliar na saúde do fígado e no controle de inflamações.', NULL, 'DENTELEAO.JPEG'),
(196, 'Chá desincha em sashe', 'Composta por fibras, Vitamina B1, colina, Ácido fólico, Vitamina C flavonoides e betacaroteno. Ela pode ajudar na digestão, inchaço e náusea.', NULL, 'DESINCHACHA.JPEG'),
(197, 'Chá detox verde', 'Rico em polifenóis, possui ação anti-oxidante. Seu uso tradicional mostra sua ação em desintoxicar, desinchar, acelerar o metabolismo e queimar gordura.', NULL, 'DETOXVERDE.JPEG'),
(198, 'Chá de erva doce', 'Ajuda na digestão, aliviando sintomas como gases e inchaço. Também tem propriedades calmantes, sendo benéfica para relaxamento e alívio de cólicas.\r\n', NULL, 'ERVADOCE.JPEG'),
(199, 'chá de erva mate ', 'Rica em cafeína, proporciona energia e disposição. Também é antioxidante e pode ajudar a melhorar a concentração e a digestão.\r\n', NULL, 'ERVAMATE.JPEG'),
(200, 'Chá erva de são joão ', 'Auxilia no tratamento de depressão leve a moderada, promovendo um equilíbrio no humor. Também pode ser útil para aliviar sintomas de ansiedade e melhorar a qualidade do sono.', NULL, 'ERVASAOJOAO.JPEG'),
(201, 'Chá espinheira santa ', 'É usada para tratar problemas digestivos, como gastrite e úlcera, pois ajuda a proteger a mucosa do estômago. Também tem propriedades anti-inflamatórias.', NULL, 'ESPINHEIRASANTA.JPEG'),
(202, 'Chá de feno grego ', 'Auxilia na regulação dos níveis de açúcar no sangue e também tem propriedades anti-inflamatórias. Pode contribuir para melhorar a digestão e fortalecer o sistema imunológico.', NULL, 'FENOGREGO.JPEG'),
(203, 'Chá de guaco ', 'Ajuda a aliviar sintomas de tosse, asma e bronquite, graças às suas propriedades expectorantes. Também possui ação anti-inflamatória, contribuindo para o alívio de dores.', NULL, 'GUACO.JPEG'),
(204, 'Chá de hibisco ', 'Prevenir e controlar a hipertensão arterial leve e moderada é uma das virtudes da erva perfumada, que pode favorecer o relaxamento dos vasos sanguíneos.', NULL, 'HIBISCO.JPEG'),
(205, 'Chá de hortelã ', 'Melhora a digestão, alivia cólicas e reduz a inflamação. Seu sabor refrescante também é ótimo para melhorar o hálito e aliviar dores de cabeça.', NULL, 'HORTELA.JPEG'),
(206, 'Chá de ipê-roxo', 'Promovendo ação anti-inflamatória, analgésica, antiviral, antifúngica, antioxidante, antibiótica e antineoplásica, ajuda a fortalecer a imunidade, sendo assim, melhor protegendo o organismo.', NULL, 'IPEROXO.JPEG'),
(207, 'Chá de maçã', 'Contribui com um sabor doce e suave aos chás, além de ser rica em antioxidantes e ajudar na digestão. Também possui propriedades anti-inflamatórias e diuréticas.', NULL, 'MACAPARACHA.JPEG'),
(208, 'Chá de melissa ', 'Ajuda a acalmar e aliviar o estresse, promovendo uma sensação de bem-estar e tranquilidade. Também pode ser útil para melhorar a qualidade do sono e aliviar sintomas de ansiedade.', NULL, 'MELISSA.JPEG'),
(209, 'Chá de mulungu ', 'Alívio de quadros leves de insônia, ansiedade e estresse.', NULL, 'MULUNGU.JPEG'),
(210, 'Chá ora-pro-nóbis', 'Rica em proteínas e fibras, auxilia na digestão e no fortalecimento do sistema imunológico. Também é uma excelente fonte de vitaminas e minerais.', NULL, 'ORAPRONOBIS.JPEG'),
(211, 'Chá passiflora ', 'Ajuda a acalmar e reduzir os níveis de estresse e ansiedade. Também pode ser benéfica para melhorar o sono e aliviar', NULL, 'PASSIFLORA.JPEG'),
(212, 'Chá de sucupira ', 'Ajuda a aliviar dor de garganta e a amigdalite, pois tem ação anti-inflamatória, que reduz o inchaço das amígdalas.', NULL, 'SUCUPIRA.JPEG'),
(213, 'Chá verde importado ', 'Ajuda a prevenir o câncer,fortalece o sistema imunológico,ajuda a prevenir diabetes,pode ajudar na perda de peso, contribui para a prevenção de doenças cardíacas e circulatórias. \r\n', NULL, 'VERDEIMPORTADO.JPEG'),
(214, 'Chá verde nacional ', 'É rico em antioxidantes, acelerando o metabolismo e favorecendo a perda de peso. Também ajuda a prevenir doenças e combater o envelhecimento celular.', NULL, 'VERDENACIONAL.JPEG'),
(215, 'Amêndoa crua ', 'Deixa os níveis de glicemia mais controlados, além de garantir ao organismo melhor aproveitamento de nutrientes. A amêndoa crua auxilia muito também contra queda de cabelo e na saúde da pele, eliminando manchas e espinhas com o seu consumo regular', NULL, 'AMENDOACRUA.JPEG'),
(216, 'Amêndoa defumada ', ' Possui vitamina E, ácido fólico e arginina, um aminoácido prescrito para o relaxamento dos vasos e o equilíbrio da pressão arterial.', NULL, 'AMENDOADEFUMADA.JPEG'),
(217, 'Amêndoa torrada com sal', 'Lanche repleto de nutrientes, destacando-se por serem ricas em proteínas, vitamina E e magnésio. Contribuem para o fortalecimento imunológico e equilíbrio do açúcar no sangue. Seu consumo auxilia na manutenção de um peso equilibrado, fornecendo energia sustentável.', NULL, 'AMENDOATORRADACOMSAL.JPEG'),
(218, 'Amêndoa torrada sem sal ', 'Ajuda a proteger os ossos e a combater o envelhecimento precoce. ', NULL, 'AMENDOATORRADASEMSAL.JPEG'),
(219, 'Avelã crua ', 'Estimula o fortalecimento do cérebro e da memória: a Avelã é rica em zinco, ácido fólico e magnésio, compostos que auxiliam a transmissão de impulsos nervosos.', NULL, 'AVELACRUA.JPEG'),
(220, 'Castanha caju com sal ', ' Ela é fonte de ômega 3, responsável por potencializar o sistema imunológico, além de reduzir o colesterol ruim e aumentar o bom.', NULL, 'CAJUCASTANHACOMSAL.JPEG'),
(223, 'Castanha caju sem sal ', 'Contém zinco, e as vitaminas A e E, o zinco em sua composição ajuda a prevenir ou amenizar sintomas de depressão; Mantém a pele bonita e saudável: e o mesmo efeito também favorece o cabelo e as unhas.', NULL, 'CASTANHACAJUSEMSAL.JPEG'),
(224, 'Macadamia sem sal ', 'Rica em ácidos graxos e ômega 3. Por isso, ela apresenta várias propriedades benéficas principalmente para o sistema cardiovascular. Além disso, é fonte de vitaminas e minerais como vitamina C, vitamina A, vitamina E, vitaminas do complexo B, fósforo e potássio.', NULL, 'MACADAMIASEMSAL.JPEG'),
(225, 'Mix agridoce ', 'Presença de vitaminas E e do complexo B e minerais, como zinco, fósforo, cobre e manganês. Perfeito para consumir entre as refeições, proporcionando energia e saciedade. ', NULL, 'MIXAGRIDOCE.JPEG'),
(226, 'Mix de castanhas ', 'O mix de castanhas traz oleaginosas ricas em triptofano, um aminoácido que contribui na produção de serotonina e melatonina', NULL, 'MIXCASTANHAS.JPEG'),
(227, 'Noz pecã agridoce ', 'Elas fortalecem as defesas do corpo, auxiliam na formação de glóbulos vermelhos, ajudam a curar ferimentos mais depressa, fortalecem ossos e dentes e, ainda, atuam contra o envelhecimento das células.', NULL, 'NOSPECANAGRIDOCE.JPEG'),
(228, 'Nozes inteiras ', 'ajudam a fortalecer o nosso sistema imunológico, auxiliam na formação de glóbulos vermelhos, ajudam a curar ferimentos mais depressa, fortalecem ossos e dentes e atuam para prevenir o envelhecimento das células.', NULL, 'NOZESINTEIRAS.JPEG'),
(229, 'nozes partidas', 'Ajudam a fortalecer o nosso sistema imunológico, auxiliam na formação de glóbulos vermelhos, ajudam a curar ferimentos mais depressa, fortalecem ossos e dentes e atuam para prevenir o envelhecimento das células.', NULL, 'NOZESPARTIDAS.JPEG'),
(230, 'Pistache crua ', 'Ajuda na regulação da saciedade e controle de peso. Como o pistache tem conteúdo rico em fibras, proteínas e ácidos graxos insaturados, e uma estrutura física crocante, ele pode induzir à saciedade, o que levaria à redução na ingestão de outros alimentos', NULL, 'PISTACHECRUA.JPEG'),
(231, 'Pistache torrado ', 'Ajuda na regulação da saciedade e controle de peso. Como o pistache tem conteúdo rico em fibras, proteínas e ácidos graxos insaturados, e uma estrutura física crocante, ele pode induzir à saciedade, o que levaria à redução na ingestão de outros alimentos', NULL, 'PISTACHETORRADO.JPEG'),
(232, 'Arroz arbóreo ', 'É rico em fibras e potássio, estudos mostram que o consumo de alimentos integrais reduz o risco de câncer e infarto. Arroz parboilizado: lotado de vitamina B, importante para afastar as doenças cardiovasculares.', NULL, 'ARROZARBOREO.JPEG'),
(233, 'Gergelim com casca ', 'O alimento com casca ajuda a aumentar Movimento intestinal e ativa a circulação sanguínea na parede intestinal. É indicado armazenar as sementes de gergelim em um recipiente hermético em local seco e sem exposição à luz. Isso irá garantir maior frescor, além de preservar os nutrientes e evitar a rancificação de óleo.', NULL, 'GERGELIMCOMCASCA'),
(234, 'Gergelim preto ', 'Promove bem-estar. Entre as substâncias presentes na semente estão o triptofano e a tiamina. Ambos são estimulantes da produção de serotonina, hormônio responsável pelas sensações de bem-estar do cérebro. Além disso, o cálcio e magnésio presentes no gergelim ajudam a reduzir a ansiedade', NULL, 'GERGELIMPRETO.JPEG'),
(235, 'Grão-de-bico ', 'Sua ingestão auxilia na redução dos triglicérides e do colesterol ruim, relacionados à obstrução dos vasos sanguíneos. Além disso, o potássio presente no alimento tem efeito vasodilatador, o que ajuda a diminuir a pressão arterial e a proteger a saúde do coração.', NULL, 'GRAOBICO.JPEG'),
(236, 'lentilha síria', 'É um fonte de proteína vegetal, rica em fibras e vitaminas como zinco e ferro. Ajuda a combater o diabetes, a osteoporose, além de ajudar a prevenir e tratar a anemia e desintoxica o organismo', NULL, 'LENTILHASIRIA.JPEG'),
(237, 'Lentilha verde ', 'É importante fonte de proteínas, vitaminas e minerais, como cálcio e ferro. Ela também é rica em fibras o que ajuda no bom funcionamento do trato digestivo e pode contribuir positivamente para a perda de peso.', NULL, 'LENTILHAVERDE.JPEG'),
(238, 'Linhaça dourada ', 'Controle da glicemia,Controle do colesterol,Melhora da pressão arterial,Auxílio na redução e controle do peso', NULL, 'LINHACADOURADA.JPEG'),
(239, 'Linhaça marrom ', 'Rica em ômega 3 e fonte de magnésio e fibras, que são importantes para um bom funcionamento intestinal e para a saúde do coração e do cérebro. Por ser um dos poucos alimentos de origem vegetal com alto conteúdo de ômega 3, essa semente é ótima alternativa para atingir a necessidade diária desse nutriente. ', NULL, 'LINHACAMARROM.JPEG'),
(240, 'Mix quinoa ', 'É uma boa fonte de fibras, que contribuem para o bom funcionamento do intestino e auxilia na absorção do colesterol e da glicose.', NULL, 'MIXQUINOA.JPEG'),
(241, 'Quinoa branca ', 'Tem ação antioxidante, que ajuda a combater os radicais livres e a prevenir doenças como câncer, doenças inflamatórias e alergias. Por causa das gorduras ômega 3 e ômega 6, pode ajudar na prevenção de doenças cardiovasculares.', NULL, 'QUINOABRANCA.JPEG'),
(242, 'Semente de abóbora crua ', 'Uma excelente fonte de ômega-3, no qual exerce uma ação anti-inflamatória contra os processos de estresse ou de doenças que possam estar causando um estado do inflamação do corpo, ajudando a proteger o organismo de doenças cardiovasculares e cerebrais e melhorando a memória e a disposição.', NULL, 'SEMENTEABOBORACRUA.JPEG'),
(243, 'Semente de abóbora torrada ', 'Contém vitamina E, vitaminas do complexo B, vitamina A, ácido fólico, potássio, cobre, ferro e magnésio. É ideal para ser consumida como aperitivo no dia a dia, também pode ser adicionada a saladas e acompanhada de frutas.', NULL, 'SEMENTEABOBORATORRADA.JPEG'),
(244, 'Semente de chia ', 'Por ter ótimas quantidades de cálcio, potássio e magnésio, a chia ajuda a manter a saúde dos ossos, prevenindo a osteopenia e a osteoporose, além de complicações, como quedas e fraturas.', NULL, 'SEMENTEDECHIA.JPEG'),
(245, 'Semente de girassol', 'Faz bem para quem tem níveis elevados de colesterol devido à sua composição ter ômega-6, ômega-9 e vitamina E, elementos que evitam a fixação desta gordura nas paredes das artérias e, consequentemente, previnem acidente vascular cerebral (AVC) e infarto.', NULL, 'SEMENTEGIRASSOL.JPEG'),
(246, 'Soja em grão', 'Além do alto valor proteico, o grão oferece muitos benefícios à saúde de uma forma geral, como redução dos níveis do colesterol ruim, o LDL, manutenção da saúde óssea e também melhora do trânsito intestinal, graças à presença de fibras no alimento.', NULL, 'SOJAGRAO.JPEG'),
(247, 'Açaí em pó', 'Rico em antioxidantes e gorduras saudáveis, ajuda na saúde cardiovascular e combate o envelhecimento celular.', NULL, 'ACAIPO.JPEG'),
(248, 'Amido de milho', 'Ótima para espessar molhos e preparações, é uma alternativa sem glúten.', NULL, 'AMIDOMILHO.JPEG'),
(249, 'Bicarbonato de sódio ', 'Usado como fermento em receitas e tem propriedades alcalinizantes para o organismo.', NULL, 'BICARBONATOSODIO.JPEG'),
(250, 'Cacau em pó', 'Rico em antioxidantes, melhora o humor e contribui para a saúde cardiovascular.', NULL, 'CACAUPO.JPEG'),
(251, 'Colágeno hidrolisado ', 'Auxilia na saúde da pele, articulações e fortalecimento de unhas e cabelos.', NULL, 'COLAGENOHIDROLISADO.JPEG'),
(252, 'Colágeno verisol', ' A suplementação com este tipo de colágeno estimula diretamente a formação da matriz extracelular da pele, o que pode ajudar a reduzir a celulite.', NULL, 'COLAGENOVERISOL.JPEG'),
(253, 'Farelo de aveia ', 'Rico em beta-glucanas, ajuda no controle do colesterol e promove saciedade.', NULL, 'FARELOAVEIA.JPEG'),
(254, 'Farinha de amêndoa ', 'Rica em gorduras saudáveis e proteínas, ajuda na saúde cardiovascular e na saciedade.', NULL, 'FARINHAAMENDOA.JPEG'),
(255, 'Farinha de arroz ', 'Sem glúten, é uma boa alternativa para dietas restritivas e de fácil digestão.', NULL, 'FARINHAARROZ.JPEG'),
(256, 'Farinha de arroz integral', 'Fonte de fibras e antioxidantes, ajuda na digestão e é uma alternativa sem glúten.', NULL, 'FARINHAARROZINTEGRAL.JPEG'),
(257, 'Farinha de aveia', 'Rica em fibras solúveis, ajuda a controlar os níveis de colesterol e melhora a digestão.', NULL, 'FARINHAAVEIA.JPEG'),
(258, 'Farinha de banana-verde', 'Rica em fibras e prebióticos, ajuda na saúde intestinal e no controle da glicemia.', NULL, 'FARINHABANANAVERDE.JPEG'),
(259, 'Farinha de berinjela', 'Ajuda no controle do colesterol, além de ser rica em fibras, auxiliando na digestão e na saciedade.', NULL, 'FARINHABERINGELA.JPEG'),
(260, 'Farinha de coco', 'Fonte de fibras e com baixo índice glicêmico, ajuda na saúde intestinal e controle da glicemia.', NULL, 'FARINHACOCO.JPEG'),
(261, 'Farinha grão-de-bico', 'Fonte de proteínas e fibras, auxilia na saciedade e no controle glicêmico.\r\n', NULL, 'FARINHAGRAOBICO.JPEG'),
(262, 'Farinha de linhaça dourada', 'Excelente fonte de ômega-3 e fibras, melhora a saúde do coração e regula o trânsito intestinal.', NULL, 'FARINHALINHACADOURADA.JPEG'),
(263, 'Farinha de linhaça marrom', 'Fonte de fibras e ômega-3, contribui para a saúde do coração e melhora o trânsito intestinal.', NULL, 'FARINHALINHACAMARROM.JPEG'),
(264, 'Farinha de maracujá', 'Rica em fibras solúveis, auxilia no controle do colesterol e glicemia.', NULL, 'FARINHAMARACUJA.JPEG'),
(265, 'Farinha panko', 'Dá crocância aos pratos e pode ser uma alternativa mais leve em comparação a outras farinhas.', NULL, 'FARINHAPANKO.JPEG');
INSERT INTO `produtos` (`CODIGO`, `NOME`, `DESCRICAO`, `PRECO`, `FOTO`) VALUES
(266, 'Farinha de soja ', 'Fonte de proteínas vegetais e isoflavonas, que ajudam no equilíbrio hormonal.\r\n', NULL, 'FARINHASJA.JPEG'),
(267, 'Farinha de trigo integral', 'Rica em fibras e nutrientes, melhora a digestão e ajuda no controle da glicemia.', NULL, 'FARINHATRIGOINTEGRAL.JPEG'),
(268, 'Farinha de uva ', 'Rica em antioxidantes e fibras, contribui para a saúde cardiovascular e intestinal.', NULL, 'FARINHAUVA.JPEG'),
(269, 'Gelatina em pó sem sabor', 'Rica em colágeno, contribui para a saúde da pele, ossos e articulações.', NULL, 'GELATINAPOSEMSABOR.JPEG'),
(270, 'Germen de trigo ', 'Rico em vitaminas E e do complexo B, contribui para a saúde da pele, dos cabelos e do sistema nervoso.', NULL, 'GERMENTRIGO.JPEG'),
(271, 'Goma xantan ', 'Estabilizante usado em receitas sem glúten para dar elasticidade e melhorar a textura.\r\n', NULL, 'GOMAXANTAN.JPEG'),
(272, 'Levedo de cerveja', 'Rico em vitaminas do complexo B e proteínas, auxilia no fortalecimento do sistema imunológico e na saúde da pele e dos cabelos.', NULL, 'LEVEDOCERVEJA.JPEG'),
(273, 'Mix de farinha sem glúten', 'Mistura de farinhas que facilita a preparação de receitas sem glúten.', NULL, 'MIXFARINHASEMGLUTEN.JPEG'),
(274, 'Polvilho azedo ', 'Ingrediente típico brasileiro, usado para dar leveza e crocância a receitas sem glúten.', NULL, 'POLVILHOAZEDO.JPEG'),
(275, 'Polvilho doce ', 'Utilizado em receitas sem glúten, ajuda a dar estrutura a pães e massas.\r\n', NULL, 'POLVILHODOCE.JPEG'),
(277, 'Trigo para kibe ', 'Rico em fibras e proteínas, contribui para a saciedade e melhora a digestão.\r\n', NULL, 'TRIGOKIBE.JPEG');

-- --------------------------------------------------------

--
-- Estrutura para tabela `receitas`
--

CREATE TABLE `receitas` (
  `NOME_RECEITA` varchar(80) NOT NULL,
  `NUMERO_RECEITA` int(11) NOT NULL,
  `INGREDIENTES` varchar(880) DEFAULT NULL,
  `PREPARO` varchar(1089) DEFAULT NULL,
  `FOTO` varchar(50) DEFAULT NULL,
  `PRODUTOS_UTILIZADOS` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `receitas`
--

INSERT INTO `receitas` (`NOME_RECEITA`, `NUMERO_RECEITA`, `INGREDIENTES`, `PREPARO`, `FOTO`, `PRODUTOS_UTILIZADOS`) VALUES
('Bolinho de lentilha com brócolis ', 1, '    • 2 xícaras (chá) de lentilha cozida com pouco caldo\r\n    • 1/2 xícara (chá) de farinha de aveia\r\n    • 1/2 xícara (chá) de brócolis cozido e picado\r\n    • 1/2 xícara (chá) de cebola picada\r\n    • 2 colheres (sopa) de cheiro verde picado\r\n    • 1/4 xícara (chá) de farinha de aveia para empanar', 'Amasse a lentilha com um garfo, numa vasilha, junte todos os ingredientes e misture até formar uma massa.\r\nModele em formato de croquete, passe no farelo e aveia e coloque numa assadeira untada com azeite. \r\nAdicione um fio de azeite por cima, e asse em forno pré-aquecido a 180 graus, por 30 minutos, ou até dourar.', 'bolinhoLentinhaBrocolis.png', 237),
('Brownie de grão-de-bico', 2, '1 e ½ xícara de grão-de-bico cozido\r\n    • 3 colheres (sopa) de açúcar mascavo\r\n    • 3 colheres (sopa) de óleo\r\n    • 3 colheres (sopa) de cacau em pó\r\n    • Extrato de baunilha a gosto\r\n    • 100ml de água quente\r\n    • 70g de aveia\r\n    • 1 colher (sopa) de fermento em pó\r\n    • Nozes (opcional)', 'Coloque o grão-de-bico cozido, a água, o óleo, o cacau em pó e o extrato de baunilha em um processador de alimentos. \r\nBata tudo até virar uma pasta homogênea. \r\nDepois, acrescente a aveia e o fermento em pó e misture.\r\nPasse a massa para uma forma antiaderente. \r\nSe preferir, pode acrescentar nozes picadas a gosto. \r\nDepois, leve ao forno preaquecido a 180°C por 20 a 25 minutos. \r\nPara verificar se já está pronto, basta espetar um palito no brownie. \r\nSe o palito sair só um pouquinho sujo de massa, está pronto!\r\n', 'brownieGraoBico.png', 235),
('Risoto queijo parmesão ', 3, '  • colheres (sopa) de manteiga\r\n    • 100 gramas de cebola;\r\n    • 1 pitada de sal;\r\n    • azeite;\r\n    • 100 gramas de queijo parmesão;\r\n    • 1 litro de caldo de carne quente;\r\n    • 100 gramas de tomate seco;\r\n    • 2 xícaras de arroz arbóreo', 'Basta colocar a manteiga, o sal, a cebola e o azeite e refogar por alguns segundos. \r\nDepois é hora de acrescentar o arroz arbóreo sem lavar.\r\n O amido solta um creme durante o cozimento, por isso o risoto ideal só pode ser feito com esse arroz. \r\nDepois de 15 minutos, basta acrescentar o tomate seco e o queijo.', 'RisotoArrozArboreo.png', 232),
('Legumes com quinoa e molho tahine ', 4, '\r\n    • 5 coxas de frango\r\n    • 1 cebola em cubos\r\n    • ½ cenoura em cubos\r\n    • 2 talos de aipo fatiados\r\n    • ¼ de pimenta dedo-de-moça fatiado Tomilho, louro, alecrim\r\n    • 2 colheres de açafrão da terra (cúrcuma)\r\n    • 1 colher de extrato de tomate \r\n    • 2 litros de água fervente \r\n    • 1 colher de alho picado \r\n    • 1 colher de gengibre ralado\r\n    •  Sal e pimenta-do-reino a gosto \r\n    • ½ brócolis americano \r\n    • 250 gramas de quinoa royal \r\n    • 4 colheres de cebola picada grossa \r\n    • 250 gramas de parmesão ralado \r\n    • 100 gramas de gorgonzola em cubos\r\n    •  Suco de 1 limão siciliano\r\n    • Sal e pimenta-do-reino a gosto \r\n    • Salsa picada \r\n    • Parmesão Raspa de limão \r\n    • Siciliano Azeite ', 'Para o caldo de legumes: Sue todos legumes e ervas no azeite. \r\nJunte o açafrão da terra, extrato de tomate, gengibre e alho. \r\nMolhe com a água fervente. \r\nTempere as coxas de frango com sal e pimenta-do-reino e coloque na panela.\r\n Cozinhe em fogo baixo tampado durante 30 minutos. \r\nRetire as coxas de frango do caldo, deixe esfriar e depois desfie.\r\n Para o brócolis: \r\nFerva água e coloque sal. \r\nCorte o brócolis em pedaços e jogue na água fervente. \r\nCozinhe por 3 minutos. \r\nJogue na água gelada (choque térmico). \r\nRetire da água e pique. \r\nPara o risoto: \r\nPuxe no azeite a cebola. \r\nJunte a quinoa e refogar por 2 minutos. \r\nColoque pouco a pouco o caldo fervendo peneirado até a quinoa ficar al dente (15 minutos). \r\nJunte parmesão e gorgonzola e cozinhe mais 5 minutos. \r\nFinalize com o limão. \r\nVerifique o sal e pimenta-do-reino. \r\nPara o toque final: \r\nFinalize o risoto com frango desfiado e brócolis. Coloque o risoto de quinoa no prato fundo. Rale parmesão e limão em cima. Decore com brócolis. Regue com um fio de azeite.', 'legumesQuinoaBranca.png', 241),
('Sopa de lentilha vermelha ', 5, '      \r\n    • 1 cebola cortada\r\n    • 2 batatas cortada (pedaços pequenos)\r\n    • 1 cenoura cortada (pedaços pequenos)\r\n    • 1 copo de lentilha vermelha\r\n    • 4 copos de água\r\n    • 1 colher (sopa) de pimenta síria\r\n    • 2 colheres (sopa) de cominho\r\n    • 1/2 colher (sopa) de sal\r\n    • 1 xícara (café) de suco de limão\r\n    • 1 xícara (chá) de azeite', 'Fritar a cebola, a batata e a cenoura, utilizando metade da quantidade do azeite.\r\nUtilize a panela de pressão. \r\nLave bem a lentilha e adicione na panela, junto com os temperos (pimenta síria, cominho e sal). \r\n Coloque a água na panela de pressão mexa bem e deixe cozinhar por 30 minutos no fogo baixo. \r\n Abra a panela, adicione o suco de limão e o resto do azeite e bata tudo com o mixer.\r\n Sirva quentinha!\r\n', 'sopaLentilhaVermelha.png', 236),
('Panqueca fit com whey de cacau', 6, '4 bananas-maçãs (ou 2 bananas-pratas ou 2 bananas-nanicas) bem maduras\r\n  2 ovos\r\n  4 colheres de sopa de farinha de amêndoas\r\n  1 scoop de Whey sabor cacau\r\n  2 colheres de sopa de semente de girassol\r\n  Noz-pecã a gosto\r\n  Mel e frutas vermelhas a gosto\r\n', 'Reúna todos os ingredientes;\r\nEm um recipiente, amasse bem as bananas;\r\nAdicione os ovos, a farinha, o Whey e as sementes. Misture até incorporar;\r\nUnte uma frigideira com um pouco de azeite, deixe aquecer e, em seguida, despeje uma porção da massa;\r\nDeixe assar bem e depois vire para dourar o outro lado. Repita o processo até a massa acabar;\r\nDecore com a noz-pecã, as frutas vermelhas, o mel e sirva.\r\n    Bom apetite!', 'panquecaCacauSementeGirassol.png', 245),
('Farofa de semente de abóbora ', 7, '   • Sementes de abóbora\r\n    • 2 colheres (sopa) de manteiga\r\n    • 1 xícara (chá) de farinha de mesa (farinha de mandioca)\r\n    • Cheiro-verde a gosto\r\n    • Sal a gosto', '   Leve as sementes secas para temperar em uma frigideira, apenas com sal.\r\n     Reserve.\r\n    Coloque manteiga e farinha de mesa em uma panela e em seguida acrescente a sementes torradas e o cheiro verde.\r\n    Misture bem até dourar.', 'farofaSementeAboboraTorrada.png', 243),
('Salada de trigo em grão ', 8, '  • 1 xícara de chá de trigo em grão1 tomate picado\r\n    • 1 cenoura pequena picada\r\n    • 1 colher de sopa de cebola picada\r\n    • Azeite\r\n    • Pimenta do reino\r\n    • Orégano\r\n    • Cebolinha picada\r\n    • Sal a gosto', 'Coloque o trigo em grãos de molho na água por 4 horas.\r\n  Lave o grão e cozinhe durante 30 minutos ou até o grão amolecer.\r\n  Escorra o grão e aguarde esfriar.\r\n  Misture os outros ingredientes.', 'GermenTrigo.png', 270),
('Patê de semente de girassol', 9, 'Ingredientes:\r\n1 xícara de semente de girassol (crua e sem casca)\r\n2 colheres de sopa de sumo de limão\r\n2 colheres de sopa de azeite*\r\n1/4 colher de chá de sal (ou a gosto)\r\n1 dente de alho pequeno\r\n2 colheres de sopa de água\r\nPimenta do reino a gosto\r\nOpcional: ervas finas/azeitona/pimenta calabresa/páprica defumada/nutritional yeast/etc', 'Deixe as sementes de molho na água fria por 8 horas (ou 1 hora em água quente), lave bem e escorra\r\nBata todos os ingredientes no processador ou no liquidificador* por 2-3 minutos ou até chegar na textura desejada.\r\nArmazene em um pote limpo e fechado na geladeira por até 5 dias.', 'pategirassol.jpeg', 245),
('Sorvete low carb de pistache', 10, '\r\n2 unidades de Ovo de galinha cru\r\n30 gramas de Pistache\r\n2 colheres (sopa) de Xilitol\r\n200 gramas de Creme de leite fresco pasteurizado\r\n1 colher (chá) de Essência de baunilha\r\n', 'Primeiro triture o pistache no processador ou liquidificador até que vire quase uma farinha. Deixe alguns pedaços ligeiramente grandes para dar uma crocância ao sorvete. Em uma panela com o fogo desligado coloque os ovos, a baunilha, o adoçante e o pistache já triturado. Ligue o fogo e mantenha ele baixo. Cozinhe por alguns minutos até que engrosse e vire um creme e reserve. Depois que o creme já estiver frio, acrescente o creme de leite fresco e misture. Coloque em um ramequim ou em uma taça e leve para gelar por pelo menos 2 horas no freezer. Se desejar salpique chocolate branco sem açúcar por cima\r\n\r\n', 'sorvetelowcarbdepistache.jpg', 230),
('Pudim de chia com banana e nozes ', 11, '1/3 de xícara de chá de leite de amêndoas\r\n2 colheres de sopa de sementes de chia\r\n1/2 xícara de chá de iogurte natural\r\n1 banana cortada em fatias\r\nMel e nozes picadas a gosto\r\n', 'Em um recipiente, misture o leite de amêndoas, as sementes de chia e o mel. Deixe descansar na geladeira por pelo menos 30 minutos ou até que a mistura tenha engrossado. Em potes individuais, coloque uma camada de banana, nozes, iogurte e pudim de chia. Finalize com uma camada de iogurte, banana e nozes. Sirva gelado.\r\n', 'pudimchiacombananaenozes.jpg', 244),
('Iogurte de macadâmia  ', 13, ' 1 xícara de macadâmias sem sal e cruas\r\n 2 xícaras de água mineral\r\n 3 colheres de sopa de suco de limão siciliano\r\n 1 colher de chá de ágar-ágar, raspas de limão a gosto e água\r\n', 'Deixar as macadâmias de molho por no mínimo 6 horas ou fazer 1 molho rápido com água morna por 1 hora. Descartar a água do molho, lavar bem e colocar no liquidificador. Numa panela adicionar as 2 xícaras de água mineral e o ágar-ágar e deixar ferver por 3 minutos, mexendo sempre. Rapidamente desligar a chama e despejar no liquidificador para bater com as macadâmias por aproximadamente 3 minutos até ficar bem liso. Despejar a mistura num recipiente de vidro, colocar o suco de limão e as raspas opcionais. Refrigerar por no mínimo 3 horas e a base está pronta.\r\n', 'iorgutemacadamia.jpg', 224),
('Biscoito de aveia com castanha de caju', 14, '1 ovo\r\nmanteiga sem sal\r\n1/2 colher (sopa) de manteiga sem sal\r\naçúcar mascavo\r\n1 colher (chá) de açúcar mascavo\r\nfarinha de aveia\r\n2 xícaras (chá) de farinha de aveia\r\ncastanha de caju\r\n50 g de castanha de caju\r\n', 'Primeiro bata o ovo sozinho.\r\nLogo após, bata a manteiga, a farinha e o açúcar, respectivamente (um de cada vez).\r\nQuebre a castanha de caju em alguns pedaços (não precisa triturar, é bom deixar em pedaços pequenos para que se possa sentir melhor o gosto).\r\nEm seguida, misture tudo até que crie consistência para formar os biscoitos.\r\nQuando a massa estiver pronta, faça os biscoitos do tamanho de 1/2 colher de sopa (pegue 1/2 colher de sopa da massa, coloque na palma da mão, enrole e dê uma achatadinha).\r\nEm seguida, coloque na forma e leve ao forno preaquecido a 180º C durante aproximadamente 15 minutos.\r\nApós esse tempo, está pronto!\r\n', 'biscoitodeaveiacomcastanha.jpg', 223),
('Leite de amêndoas', 15, '\r\n1 xícara amêndoas cruas\r\n4 xícara água mineral\r\n', 'Deixar as amêndoas de molho na água durante uma noite.\r\nEscorrer as amêndoas e enxaguar.\r\nBater as amêndoas no liquidificador com 4 xícaras de água.\r\nCom ajuda de um pano limpo ou saquinho de voal, coar o leite de amêndoas. Utilizar uma colher para empurrar e aproveitar todo o líquido. Espremer quando chegar ao fim.\r\nE se servir.\r\n', 'leitedeamendoas.jpg', 215),
('Pão de pistache ', 16, '1 ovo\r\n2 colheres de sopa de farinha de espelta \r\n1 colher de sopa farinha de linhaça\r\n1 colher de café de fermento químico em pó (fermento para bolo)\r\n1 colher de sopa pistaches triturados grosseiramente\r\n', 'Em uma vasilha coloque o ovo, as farinhas e bata bem.\r\nJunte o fermento e misture delicadamente.\r\nAcrescente o pistache e misture novamente.\r\nTransfira a massa para uma frigideira untada, tampe e leve para cozinhar em fogo baixo até os dois lados ficarem douradinhos.\r\nRecheie com o que preferir e aproveite .\r\n', 'paodepisache.jpg', 230),
('Brigadeiro fit com nozes e castanhas ', 17, '1/2 xícara água quente\r\n2 colheres de sopa cacau em pó solúvel\r\n1/2 xícara leite em pó desnatado\r\n2 doses Whey Protein; sabor chocolate\r\nnozes trituradas\r\ncoco ralado sem açúcar\r\nadoçante a gosto\r\n\r\n', 'Unte a panela com um pouco de margarina light. Dilua o leite no whey para dissolver bem e, depois, leve para a panela em fogo brando.\r\nAdicione em seguida o chocolate em pó e o adoçante.\r\nMexa suavemente, até que o brigadeiro comece a engrossar e desgrudar da panela. Reserve.\r\nQuando estiver frio, faça as bolinhas do tamanho de sua preferência e passe no coco ralado e nas castanhas ou nozes trituradas.\r\n', 'brigadeirodepistache.jpg', 229),
('Salada de folhas com amêndoas laminadas ', 18, 'Folhas verdes (alface, rúcula, espinafre)\r\nAmêndoas laminadas\r\nAzeite de oliva\r\nVinagre balsâmico\r\nQueijo parmesão ralado\r\n\r\n', '\r\n Em uma tigela, coloque as folhas verdes lavadas.\r\n Toste levemente as amêndoas laminadas em uma frigideira seca.\r\n Misture o azeite e o vinagre e tempere as folhas.\r\n Finalize com as amêndoas tostadas e o parmesão ralado por cima.\r\n', 'saladadefolhascomamendoas.jpeg', 218),
('Bolo de avelã', 19, ' 1 xícara de avelã crua\r\n 1 xícara de farinha de trigo\r\n 1 xícara de açúcar\r\n 3 ovos\r\n 1 colher de fermento\r\n\r\n', '\r\n Triture as avelãs até formar uma farinha.\r\n Misture a farinha de avelã com a farinha de trigo e o açúcar.\r\n Adicione os ovos e mexa até obter uma massa homogênea.\r\n Incorpore o fermento e leve ao forno a 180ºC por 30 minutos.\r\n\r\n', 'bolodeavela.jpg', 219),
('Barra de cereais com mix de castanhas ', 20, '2 xícaras de mix de castanhas\r\n 1/2 xícara de mel\r\n 1/2 xícara de aveia\r\n', ' Misture o mel, as castanhas e a aveia.\r\n Espalhe a mistura em uma forma forrada com papel manteiga.\r\n Leve ao forno a 180ºC por 20 minutos.\r\n Deixe esfriar e corte em barras.\r\n', 'barradecereais.jpg', 226),
('Torta de nozes pecã agridoce ', 21, '1 xícara de nozes pecã agridoce\r\n1/2 xícara de açúcar mascavo\r\n1/4 xícara de manteiga\r\n1 pacote de massa folhada\r\n', ' Forre uma forma com a massa folhada.\r\n Derreta a manteiga com o açúcar e as nozes pecã.\r\n Despeje sobre a massa e leve ao forno a 180ºC por 25 minutos.\r\n', 'nozespecan .jpg', 227),
('Amêndoas cruas caramelizadas ', 22, ' 1 xícara de amêndoa crua\r\n 1/2 xícara de açúcar\r\n 1 colher de sopa de água\r\n\r\n', ' Em uma frigideira, derreta o açúcar com a água.\r\n Adicione as amêndoas e mexa até ficarem caramelizadas.\r\n Espalhe as amêndoas em uma superfície untada e deixe esfriar.\r\n', 'amendoascruascaramelizadas.png', 215),
('Arroz de castanha-de-caju', 23, '1 colher (sopa) de óleo\r\n2 xícaras (chá) de arroz lavado e escorrido\r\n2 tabletes de MAGGI® Caldo Legumes\r\n4 xícaras (chá) de água fervente\r\n2 colheres (sopa) de manteiga\r\n100 g de castanhas-de-caju tostadas e picadas grosseiramente\r\n3 colheres (sopa) de salsa picada finamente\r\n\r\n', 'Em uma panela média, aqueça o óleo e refogue bem o arroz.\r\nAcrescente o MAGGI Caldo Legumes e a água fervente. \r\nDeixe cozinhar, em fogo baixo, em panela parcialmente tampada. quando o arroz estiver cozido, adicione a manteiga, as castanhas-de-caju, a salsa e misture delicadamente. \r\nTampe, aguarde 5 minutos e sirva a seguir.\r\n', 'arrozdecastanha.jpeg', 223),
('Brownie de macadâmia ', 24, '250 g de chocolate meio amargo\r\n200 g de Margarina\r\n4 ovos\r\n1/2 xícara de farinha de trigo\r\n1 e 1/2 xícara de açúcar\r\n100 g de macadâmia triturada rapidamente\r\n', 'Derreta o chocolate junto com a margarina em banho-maria e reserve.\r\nBata os ovos com o açúcar no batedor de mão e acrescente ao chocolate derretido.\r\nAdicione a farinha e continue batendo à mão.\r\nAcrescente a macadâmia e pronto: coloque em uma forma untada de margarina e farinha e leve ao forno a 180º C por 40 minutos.\r\nSirva quente com sorvete ou frio mesmo.\r\n', 'browniemacadamia.jpg', 224),
('Granola caseira com mix de castanhas ', 25, '2 xícaras de aveia em flocos\r\n1 xícara de *mix de castanhas* (castanha de caju, amêndoas, nozes, macadâmia, etc.)\r\n½ xícara de coco ralado sem açúcar\r\n¼ de xícara de mel ou xarope de bordo\r\n2 colheres de sopa de óleo de coco derretido\r\n1 colher de chá de canela em pó\r\n1 pitada de sal\r\n1 xícara de frutas secas (uvas passas, damasco picado, etc.)\r\n', 'Preaqueça o forno a 160°C e forre uma assadeira grande com papel manteiga.\r\nEm uma tigela grande, misture a aveia, o *mix de castanhas* e o coco ralado.\r\nEm uma tigela separada, misture o mel (ou xarope de bordo), o óleo de coco, a canela e o sal. Despeje a mistura de aveia e castanhas.\r\nMisture bem até que todos os ingredientes secos estejam revestidos pela calda.\r\nEspalhe a mistura de forma uniforme na assadeira e asse por 20-25 minutos, mexendo na metade do tempo para garantir que tudo doure por igual.\r\nRetire do forno e misture as frutas secas. Deixe esfriar completamente antes de armazenar em um recipiente hermético.\r\nSirva com iogurte, leite ou como um lanche crocante!\r\n', 'granola-caseira.jpg', 226),
('Patê de castanha-de-caju sem sal ', 26, '1 xícara de castanha de caju sem sal (deixe de molho em água por 4 horas)\r\n2 colheres de sopa de azeite de oliva\r\n2 colheres de sopa de suco de limão\r\n1 dente de alho\r\n¼ de xícara de água filtrada (ou mais, se necessário)\r\nSal a gosto\r\nErvas frescas picadas (opcional: salsinha, cebolinha, coentro)\r\n\r\n', 'Escorra a castanha de caju que ficou de molho e coloque-a em um processador de alimentos ou liquidificador.\r\nAdicione o azeite de oliva, o suco de limão, o dente de alho e uma pitada de sal.\r\nBata tudo até obter uma consistência cremosa. Adicione a água aos poucos até atingir a textura desejada, ajustando conforme necessário.\r\nProve e ajuste o sal ou o limão, se necessário.\r\nSe desejar, misture algumas ervas frescas picadas para um toque extra de sabor.\r\nSirva o patê com torradas, pão pita, ou como acompanhamento de vegetais crus.\r\n\r\n', 'patedecastanhadecaju.jpg', 222),
('Pão de levedo de cerveja ', 27, '3 xícaras de farinha de trigo integral  \r\n2 colheres de sopa de levedo de cerveja  \r\n1 colher de chá de sal  \r\n1 colher de sopa de azeite de oliva  \r\n1 colher de sopa de mel  \r\n1 xícara de água morna  \r\n1/2 xícara de nozes picadas (opcional)  \r\n\r\n', 'Em uma tigela grande, misture a farinha de trigo integral, o levedo de cerveja e o sal. Adicione o azeite de oliva e o mel, misturando bem. Aos poucos, despeje a água morna, mexendo até formar uma massa homogênea. Sove a massa por cerca de 10 minutos, até que fique elástica e macia. Se desejar, adicione as nozes picadas à massa durante a sova. Deixe a massa descansar em um local morno, coberta com um pano, por 1 hora, ou até dobrar de tamanho. Após crescer, modele o pão e coloque-o em uma assadeira untada. Asse em forno preaquecido a 180°C por cerca de 30 a 35 minutos, até dourar.\r\n', 'paolevedodecerveja.jpg', 272),
('Bolo de maça com farinha de amêndoa ', 28, '1 xícara de chá de farelo de aveia⁣\r\n1/2 xícara de chá de mel puro⁣\r\n1/2 xícara de chá de óleo de girassol ⁣\r\n1/3 xícara de chá de iogurte natural⁣\r\n1/3 xícara de chá de chocolate em pó (cacau 50%)\r\n1/4 xícara de chá de farinha de amêndoas\r\n1/4 xícara de café de café coado sem açúcar\r\n1 colher de chá de canela⁣\r\n1 colher de chá de fermento químico em pó (fermento para bolo)\r\n1 pitada de sal⁣\r\n2 ovos\r\n', 'Com o auxílio de uma peneira, transfira para um recipiente a aveia, o chocolate em pó, a farinha, a canela e o sal e misture-os uniformemente. Reserve.\r\nColoque em outro recipiente os ovos, o mel, o óleo, o café e o iogurte natural e mexa até formar uma mistura homogênea.\r\nJunte a mistura dos líquidos com a mistura dos secos,.\r\nAdicione o fermento e mexa delicadamente até adquirir uma massa lisa e homogênea.\r\nColoque as maçãs em uma forma untada de bolo inglês e despeje a massa do bolo.\r\nLeve ao forno preaquecido a 180 °C por 40 minutos.\r\nE está pronto! Sirva e bom apetite.\r\n', 'bolo-de-maca-farinhaamendoas.jpg', 254),
('Panqueca de farinha de banana verde ', 29, '1 xícara de farinha de banana verde  \r\n2 ovos  \r\n1/2 xícara de leite  \r\n1 colher de sopa de óleo de coco  \r\n1 colher de chá de fermento em pó  \r\n1 pitada de sal  \r\n1 colher de sopa de mel (opcional)  \r\n', 'Em uma tigela, misture a farinha de banana verde, o fermento e o sal. Em outra tigela, bata os ovos com o leite e o óleo de coco. Combine as duas misturas e mexa até obter uma massa homogênea. Se desejar, adicione mel para um toque de doçura. Aqueça uma frigideira antiaderente em fogo médio e, com o auxílio de uma concha, despeje pequenas porções da massa na frigideira. Cozinhe até as bordas começarem a soltar e a panqueca dourar. Vire e doure o outro lado. Repita o processo até a massa acabar. Sirva com frutas frescas ou mel.', 'panquecabananaverde.jpg', 258),
('Farofa com farinha panko ', 30, '1 xícara de farinha panko  \r\n2 colheres de sopa de manteiga  \r\n1 cebola picada  \r\n2 dentes de alho picados  \r\n1/4 xícara de azeitonas picadas  \r\n1/4 xícara de cenoura ralada  \r\n1/4 xícara de cheiro-verde picado  \r\nSal e pimenta a gosto  \r\n', 'Em uma frigideira grande, derreta a manteiga e refogue a cebola até ficar dourada e macia. Adicione o alho e refogue por mais 1 a 2 minutos. Acrescente a cenoura ralada e as azeitonas, mexendo bem. Aos poucos, adicione a farinha panko, mexendo constantemente para que ela toste e fique dourada. Tempere com sal e pimenta a gosto. Retire do fogo e finalize com o cheiro-verde picado. Sirva como acompanhamento de carnes ou peixes.\r\n', 'farofa-crocante-de-panko.jpeg', 265),
('Smoothie de açaí em pó', 31, '1 colher de sopa de açaí em pó  \r\n1 banana  \r\n200ml de leite vegetal (amêndoa, coco, ou outro de sua preferência)  \r\n1 colher de sopa de mel ou xarope de agave  \r\n1 colher de sopa de chia (opcional)  \r\nGelo a gosto  \r\n', 'No liquidificador, coloque o açaí em pó, a banana, o leite vegetal, o mel e a chia, se estiver usando. Bata até obter uma mistura cremosa e homogênea. Adicione gelo a gosto e bata novamente. Sirva imediatamente em um copo grande. Se quiser, decore com fatias de banana ou sementes de chia por cima.\r\n\r\n', 'Acai-Smoothie.jpg', 247),
('Bolo de farinha de berinjela ', 32, '1 xícara de farinha de berinjela  \r\n2 ovos  \r\n1/2 xícara de óleo de coco  \r\n1/2 xícara de açúcar mascavo  \r\n1 colher de chá de fermento em pó  \r\n1 colher de chá de canela em pó  \r\n1/2 xícara de leite de amêndoas  \r\n1/4 xícara de nozes picadas (opcional)  \r\n', 'Em uma tigela, misture os ovos, o óleo de coco e o açúcar mascavo até obter uma mistura homogênea. Adicione a farinha de berinjela, o fermento, a canela e o leite de amêndoas, misturando bem. Se desejar, acrescente nozes picadas para dar mais textura ao bolo. Despeje a massa em uma forma untada e enfarinhada. Asse em forno preaquecido a 180°C por cerca de 30 a 35 minutos, ou até que, ao inserir um palito no centro, ele saia limpo. Deixe esfriar antes de desenformar e servir.\r\n\r\n', 'bolofarinhaberinjela.jpg', 259),
('Pão com farinha de linhaça dourada ', 33, '1 xícara de farinha de linhaça dourada  \r\n1 xícara de farinha de arroz integral  \r\n1 colher de sopa de fermento biológico seco  \r\n1 colher de chá de sal  \r\n1 colher de sopa de azeite de oliva  \r\n1 colher de chá de açúcar mascavo  \r\n1 xícara de água morna  \r\n1 colher de sopa de sementes de chia (opcional)  \r\n', 'Em uma tigela, misture as farinhas, o fermento, o sal e o açúcar mascavo. Adicione o azeite de oliva e a água morna aos poucos, mexendo até formar uma massa uniforme. Se desejar, acrescente as sementes de chia. Sove a massa por cerca de 5 a 10 minutos, até ficar elástica. Deixe descansar em um local aquecido por aproximadamente 1 hora, ou até dobrar de tamanho. Coloque a massa em uma forma untada e leve para assar em forno preaquecido a 180°C por 35 a 40 minutos. Retire do forno e deixe esfriar antes de fatiar.\r\n\r\n', 'paodelinhaca.jpg', 262),
('Vitamina com gérmen de trigo ', 34, '1 colher de sopa de gérmen de trigo  \r\n1 copo de leite (ou leite vegetal)  \r\n1 banana madura  \r\n1 colher de sopa de mel  \r\n1 colher de sopa de aveia (opcional)  \r\nGelo a gosto  \r\n', 'No liquidificador, coloque o gérmen de trigo, o leite, a banana, o mel e a aveia, se estiver usando. Bata até que todos os ingredientes estejam bem incorporados e a mistura fique cremosa. Adicione gelo a gosto e bata novamente. Sirva imediatamente em um copo grande. Essa vitamina é ideal para um café da manhã nutritivo.\r\n', 'VitaminaGérmentrigo.jpg', 270),
('Biscoito de farinha de arroz integral ', 35, '1 xícara de farinha de arroz integral  \r\n1/2 xícara de manteiga (em temperatura ambiente)  \r\n1/4 xícara de açúcar  \r\n1 colher de chá de essência de baunilha  \r\n1 colher de sopa de sementes de gergelim (opcional)  \r\n1 pitada de sal  \r\n', 'Em uma tigela, misture a manteiga e o açúcar até obter um creme claro e fofo. Adicione a essência de baunilha e misture. Aos poucos, incorpore a farinha de arroz integral e a pitada de sal. Se desejar, adicione as sementes de gergelim. Misture bem até formar uma massa uniforme. Modele os biscoitos no formato desejado e disponha-os em uma assadeira forrada com papel manteiga. Asse em forno preaquecido a 180°C por cerca de 15 a 18 minutos, ou até que fiquem dourados nas bordas. Deixe esfriar antes de servir.\r\n', 'biscoitoarrozintegral.jpg', 256),
('Gelatina com colágeno hidrolisado', 36, '1 sachê de gelatina incolor sem sabor  \r\n1 colher de sopa de colágeno hidrolisado  \r\n1 xícara de suco natural de frutas (laranja, uva ou outro de sua preferência)  \r\n1 colher de sopa de mel (opcional)  \r\n1 xícara de água  \r\n', 'Dissolva a gelatina incolor em 1/2 xícara de água morna, mexendo bem até que todos os grãos estejam dissolvidos. Acrescente o colágeno hidrolisado e misture até incorporar. Adicione o suco de frutas e o mel, se estiver usando, e misture bem. Acrescente a outra 1/2 xícara de água fria e mexa. Despeje a mistura em potes individuais ou em uma forma grande. Leve à geladeira por cerca de 4 horas, ou até firmar completamente. Sirva gelado.\r\n', 'gelatinacolageno.jpg', 269),
('Bolo de farinha de coco', 37, '1 xícara de farinha de coco  \r\n2 ovos  \r\n1/2 xícara de leite de coco  \r\n1/4 xícara de óleo de coco  \r\n1/2 xícara de açúcar mascavo  \r\n1 colher de chá de fermento em pó  \r\n1 colher de chá de canela em pó (opcional)  \r\n\r\n', 'Em uma tigela, bata os ovos com o leite de coco e o óleo de coco até obter uma mistura homogênea. Acrescente o açúcar mascavo e continue misturando. Aos poucos, adicione a farinha de coco, o fermento e a canela. Mexa bem até formar uma massa uniforme. Despeje a massa em uma forma untada e enfarinhada. Asse em forno preaquecido a 180°C por cerca de 30 a 35 minutos, ou até que um palito inserido no centro saia limpo. Deixe esfriar antes de desenformar e servir.\r\n\r\n', 'bolofarinhadecoco.png', 260),
('Biscoito de farinha de maracujá ', 38, '1 xícara de farinha de maracujá  \r\n1/2 xícara de manteiga  \r\n1/4 xícara de açúcar  \r\n1 colher de chá de raspas de limão (opcional)  \r\n1 pitada de sal  \r\n', 'Em uma tigela, misture a manteiga e o açúcar até formar um creme leve e homogêneo. Acrescente a farinha de maracujá, as raspas de limão e a pitada de sal. Misture bem até formar uma massa firme. Modele os biscoitos no formato que preferir e disponha-os em uma assadeira forrada com papel manteiga. Asse em forno preaquecido a 180°C por cerca de 12 a 15 minutos, até que os biscoitos estejam dourados nas bordas. Deixe esfriar completamente antes de servir.\r\n\r\n', 'biscoitomaracuja.jpg', 264),
('Doce de banana e cacau ', 39, '1 banana amassada\r\nmeia colher (sopa) de cacau em pó\r\n6 colheres (sopa) de NUTREN® Fortify (60g)\r\n3 colheres (sopa) de água\r\n1 pitada de canela em pó\r\n\r\n', 'Em um recipiente refratário, coloque as bananas e leve ao micro-ondas em potência média por 30 segundos.\r\nAdicione o chocolate em pó, o NUTREN Fortify, a água e a canela, misture bem até obter uma mistura homogênea. Sirva morno ou gelado.\r\n\r\n', 'docebananacacau.jpg', 250),
('Bolo de cacau ', 40, '1 xícara de farinha de trigo integral  \r\n1/2 xícara de cacau   \r\n2 ovos  \r\n1/2 xícara de açúcar mascavo  \r\n1/2 xícara de leite  \r\n1/4 xícara de óleo de coco  \r\n1 colher de chá de fermento em pó  \r\n', 'Em uma tigela, bata os ovos com o açúcar mascavo até formar uma mistura clara e fofa. Adicione o leite e o óleo de coco, e misture bem. Acrescente a farinha de trigo integral e o cacau em pó, misturando até que a massa fique homogênea. Por último, incorpore o fermento em pó. Despeje a massa em uma forma untada e enfarinhada. Asse em forno preaquecido a 180°C por cerca de 30 minutos, ou até que um palito inserido no centro saia limpo. Deixe esfriar antes de servir.\r\n\r\n', 'bolocacaualcalino.jpg', 250),
('Mingau de aveia ', 41, '2 xícaras de leite integral\r\n3 colheres (sopa) de açúcar\r\n5 colheres de aveia flocos finos\r\ncanela para polvilhar\r\n\r\n', 'Em um copo americano coloque a aveia, o açúcar e um pouco de leite, mexa e reserve.\r\nFerva o restante do leite em uma panela e quando começar a levantar fervura coloque a mistura que você reservou.\r\nAguarde até começar a quase grudar na panela, mexendo sempre em fogo baixo e está pronto.\r\nColoque canela por cima para polvilhar e bom apetite.\r\n\r\n', 'mingauaveia.jpg', 114),
('Bolo de farinha de uva', 42, '1 xícara de farinha de uva  \r\n2 ovos  \r\n1/2 xícara de óleo  \r\n1/2 xícara de açúcar  \r\n1/2 xícara de leite  \r\n1 colher de chá de fermento em pó  \r\n', 'Em uma tigela, bata os ovos com o açúcar até obter uma mistura clara. Adicione o óleo e o leite, misturando bem. Aos poucos, incorpore a farinha de uva e o fermento, mexendo até formar uma massa homogênea. Despeje a massa em uma forma untada e asse em forno preaquecido a 180°C por cerca de 30 minutos. Faça o teste do palito para verificar o ponto. Deixe esfriar antes de servir.', 'bolouva.jpg', 268),
('Bolo de farinha de soja ', 43, '1 xícara de farinha de soja  \r\n2 ovos  \r\n1/2 xícara de leite  \r\n1 colher de sopa de óleo de coco  \r\n1 colher de chá de fermento em pó  \r\n1 pitada de sal  \r\n', 'Misture a farinha de soja, o fermento e o sal em uma tigela. Em outra tigela, bata os ovos com o leite e o óleo de coco. Misture os ingredientes secos com os líquidos até formar uma massa homogênea. Aqueça uma frigideira antiaderente em fogo médio e, com o auxílio de uma concha, despeje pequenas porções da massa. Frite as panquecas até dourar dos dois lados. Sirva com recheio doce ou salgado de sua preferência.\r\n\r\n', 'panquecafarinhasoja.jpg', 266),
('Bolo de farinha de trigo integral ', 44, '2 xícaras de farinha de trigo integral  \r\n2 ovos  \r\n1/2 xícara de açúcar mascavo  \r\n1/4 xícara de óleo de coco  \r\n1/2 xícara de leite ou leite vegetal  \r\n1 colher de chá de fermento em pó  \r\n1 colher de chá de canela em pó (opcional)  \r\n1 pitada de sal  \r\n1/2 xícara de nozes ou passas (opcional)  \r\n', 'Em uma tigela grande, bata os ovos com o açúcar mascavo até obter uma mistura homogênea. Adicione o óleo de coco e o leite, misturando bem. Acrescente a farinha de trigo integral, o fermento, a canela e o sal, e misture até que a massa fique lisa. Se desejar, acrescente as nozes ou passas. Despeje a massa em uma forma untada e enfarinhada. Asse em forno preaquecido a 180°C por 30 a 35 minutos, ou até que um palito inserido no centro saia limpo. Deixe esfriar antes de desenformar e servir.\r\n\r\n', 'bolotrigointregal.jpg', 267),
('Pão de amido de milho', 45, '1 xícara de amido de milho  \r\n1 xícara de polvilho doce  \r\n1 ovo  \r\n1/2 xícara de água morna  \r\n2 colheres de sopa de óleo de coco ou azeite  \r\n1 colher de chá de sal  \r\n1 colher de chá de fermento químico  \r\n', 'Em uma tigela, misture o amido de milho, o polvilho doce e o sal. Acrescente o ovo, o óleo e a água morna, misturando bem até formar uma massa lisa e homogênea. Por último, adicione o fermento e misture levemente. Modele os pãezinhos com as mãos e disponha-os em uma assadeira untada. Asse em forno preaquecido a 180°C por cerca de 20 a 25 minutos, até que fiquem levemente dourados. Sirva quente.\r\n', 'paoamidodemilho.jpg', 248),
('Biscoito de amido de milho', 46, '500 g de amido de milho\r\n1 caixa de leite condensado\r\n200 g de manteiga/margarina\r\n', 'Junte todos os ingredientes numa tigela;\r\nMisture tudo com as mãos, amassando bem até formar uma massa lisa e homogênea;\r\nEm seguida modele os biscoitinhos como preferir, em bolinhas, tirinhas ou use forminhas para modelar;\r\nAcomode os biscoitinhos numa forma levemente untada com manteiga (deixe um espaço de 2cm entre eles);\r\nDICA: Eu gosto de fazer bolinhas e achata-las com um garfo.\r\nLeve para assar em forno preaquecido, 180ºC, por cerca de 15 minutos ou até dourar a parte de baixo dos biscoitinhos;\r\nguarde em um pote com tampa, em local seco e arejado.\r\n', 'biscoito-amidodemilho.jpg', 248),
('Bolinho de triguilho ', 47, '1 xícara de triguilho(trigo para quibe)\r\n2 batatas cozidas e espremidas\r\n1 cebola pequena picada\r\n2 dentes de alho picados\r\n1 tomate sem sementes picado\r\n1 galhinho de hortelã\r\ncebolinha, salsinha e orégano a gosto\r\n\r\n', 'Deixar o triguilho de molho em água quente por 30 minutos.\r\nEspremer para retirar a água.\r\nEm uma vasilha misturar: triguilho,batatas espremidas,tomate e os temperos.\r\nModelar os bolinhos e fritar ou assar.\r\nSe for assar untar a assadeira com óleo ou azeite e regar os bolinhos com azeite.\r\nSe preferir, servir os bolinhos com molho de tomates.\r\n\r\n', 'bolinhodetrigulho.jpg', 277),
('Bolo de farinha de amêndoa ', 48, ' 1 xícara de farinha de amêndoa  \r\n2 ovos  \r\n1/2 xícara de açúcar de coco ou mascavo  \r\n1/4 xícara de óleo de coco ou manteiga derretida  \r\n1/4 xícara de leite ou leite vegetal  \r\n1 colher de chá de fermento em pó  \r\n1 colher de chá de essência de baunilha  \r\n', 'Em uma tigela, bata os ovos com o açúcar até formar um creme claro. Adicione o óleo de coco e o leite, misturando bem. Acrescente a farinha de amêndoa e o fermento, misturando até obter uma massa homogênea. Adicione a essência de baunilha e misture levemente. Despeje a massa em uma forma untada e leve ao forno preaquecido a 180°C por cerca de 25 minutos, ou até que o bolo esteja dourado e um palito inserido no centro saia limpo. Deixe esfriar antes de servir.\r\n', 'Bolo-amendoas.jpg', 254),
('Bolo de polvilho doce', 49, '1 xícara de polvilho doce  \r\n1 xícara de leite  \r\n2 ovos  \r\n1/4 xícara de óleo de coco ou manteiga derretida  \r\n1/4 xícara de açúcar  \r\n1 colher de chá de fermento em pó  \r\n1 pitada de sal  \r\n\r\n', 'Bata os ovos com o açúcar até formar um creme claro. Adicione o leite e o óleo de coco, e misture bem. Aos poucos, incorpore o polvilho doce e o fermento. Misture até que a massa fique homogênea. Despeje a massa em uma forma untada e leve ao forno preaquecido a 180°C por cerca de 30 minutos. Faça o teste do palito para verificar se o bolo está pronto. Deixe esfriar antes de desenformar.\r\n\r\n', 'bolopolvilhodoce.jpg', 275),
('Bolo de farinha de aveia', 50, '2 xícaras de farinha de aveia  \r\n2 ovos  \r\n1/2 xícara de leite ou leite vegetal  \r\n1/4 xícara de óleo de coco  \r\n1/2 xícara de açúcar mascavo  \r\n1 colher de chá de fermento em pó  \r\n1 colher de chá de canela em pó (opcional)  \r\n1 pitada de sal  \r\n', 'Em uma tigela, bata os ovos com o açúcar até obter uma mistura cremosa. Adicione o leite e o óleo de coco, misturando bem. Acrescente a farinha de aveia, o fermento, a canela e o sal, e misture até que a massa fique homogênea. Despeje a massa em uma forma untada e enfarinhada. Asse em forno preaquecido a 180°C por cerca de 30 a 35 minutos, ou até que um palito inserido no centro saia limpo. Deixe esfriar antes de desenformar e servir.\r\n\r\n', 'boloaveia.jpg', 257),
('Pudim com gelatina e farelo de aveia ', 51, '1 sachê de gelatina incolor sem sabor  \r\n1/2 xícara de farelo de aveia  \r\n200 ml de leite ou bebida vegetal  \r\n1 colher de sopa de mel ou adoçante (opcional)  \r\nFrutas frescas para decorar (opcional)  \r\n', 'Dissolva a gelatina incolor em 100 ml de água morna, mexendo até que esteja completamente dissolvida. Em seguida, adicione o farelo de aveia e o leite, misturando bem até que a mistura esteja homogênea. Se desejar, adicione o mel ou adoçante. Despeje a mistura em potinhos individuais ou em uma forma grande. Leve à geladeira por cerca de 4 horas, ou até que o pudim esteja firme. Decore com frutas frescas antes de servir.\r\n\r\n', 'pudimfarelodeaveia.jpg', 253),
('Bolo de laranja cristalizada', 52, '640 gramas de chocolate meio amargo picado\r\n9 colheres (sopa) de manteiga\r\n1 xícara (chá) de creme de leite fresco\r\n8 ovo grandes\r\n1 xícara (chá) de açúcar\r\n1 colher (sopa) de baunilha\r\n1/2 colher (chá) de sal\r\n1/4 xícara (chá) de laranja cristalizada\r\n3 colheres (sopa) de leite\r\n2 colheres (sopa) de glucose de milho\r\nlaranja cristalizada para decorar \r\n', 'Em uma panela, leve ao fogo baixo 480 g do chocolate, 7 colheres (sopa) de manteiga e o creme de leite, mexendo até derreter.\r\nEm uma tigela, misture os ovos com um fouet (batedor).\r\nAos poucos, junte o creme de chocolate e a manteiga, mexendo até obter uma mistura homogênea.\r\nAdicione o açúcar, a baunilha, o sal e a casca de laranja. \r\nDespeje em uma forma de bolo inglês, de 11 x 28 cm, com o fundo forrado com papel-manteiga, untado com manteiga.\r\nLeve ao forno moderado (180 °C), preaquecido, por 1 hora ou até que, ao espetar a massa com um palito, ele saia úmido.\r\nDeixe esfriar e desenforme. \r\nLeve à geladeira por, no mínimo, 2 horas.\r\nPara a cobertura, em uma panela, leve ao fogo baixo (160 ºC) mais 160 g do chocolate com 2 colheres (sopa) de manteiga, mexendo até derreter.\r\nFora do fogo, junte o leite e a glucose de milho e misture até obter um creme homogêneo.\r\nDespeje sobre o bolo e sirva, decorado com a casca de laranja cristalizada. \r\n\r\n\r\n ', 'bololaranjacristalizada.jpeg', 177);

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `produtos`
--
ALTER TABLE `produtos`
  ADD PRIMARY KEY (`CODIGO`);

--
-- Índices de tabela `receitas`
--
ALTER TABLE `receitas`
  ADD PRIMARY KEY (`NUMERO_RECEITA`),
  ADD KEY `FK_PRODUTOS_UTILIZADOS` (`PRODUTOS_UTILIZADOS`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `produtos`
--
ALTER TABLE `produtos`
  MODIFY `CODIGO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=279;

--
-- AUTO_INCREMENT de tabela `receitas`
--
ALTER TABLE `receitas`
  MODIFY `NUMERO_RECEITA` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
